// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dfuse/eosio/tokenmeta/v1/tokenmeta.proto

package pbtokenmeta

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SortOrder int32

const (
	SortOrder_ASC  SortOrder = 0
	SortOrder_DESC SortOrder = 1
)

var SortOrder_name = map[int32]string{
	0: "ASC",
	1: "DESC",
}

var SortOrder_value = map[string]int32{
	"ASC":  0,
	"DESC": 1,
}

func (x SortOrder) String() string {
	return proto.EnumName(SortOrder_name, int32(x))
}

func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_acfa679eff1c5edb, []int{0}
}

// you can sort by either: Symbol alphanumerically, holder count, market cap
type GetTokensRequest_SortField int32

const (
	GetTokensRequest_NONE       GetTokensRequest_SortField = 0
	GetTokensRequest_ALPHA      GetTokensRequest_SortField = 1
	GetTokensRequest_HOLDERS    GetTokensRequest_SortField = 2
	GetTokensRequest_MARKET_CAP GetTokensRequest_SortField = 3
)

var GetTokensRequest_SortField_name = map[int32]string{
	0: "NONE",
	1: "ALPHA",
	2: "HOLDERS",
	3: "MARKET_CAP",
}

var GetTokensRequest_SortField_value = map[string]int32{
	"NONE":       0,
	"ALPHA":      1,
	"HOLDERS":    2,
	"MARKET_CAP": 3,
}

func (x GetTokensRequest_SortField) String() string {
	return proto.EnumName(GetTokensRequest_SortField_name, int32(x))
}

func (GetTokensRequest_SortField) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_acfa679eff1c5edb, []int{0, 0}
}

// You can sort by either: Symbol alphanumerically, Token Amount, market value of tokens
type GetAccountBalancesRequest_SortField int32

const (
	GetAccountBalancesRequest_NONE         GetAccountBalancesRequest_SortField = 0
	GetAccountBalancesRequest_ALPHA        GetAccountBalancesRequest_SortField = 1
	GetAccountBalancesRequest_AMOUNT       GetAccountBalancesRequest_SortField = 2
	GetAccountBalancesRequest_MARKET_VALUE GetAccountBalancesRequest_SortField = 3
)

var GetAccountBalancesRequest_SortField_name = map[int32]string{
	0: "NONE",
	1: "ALPHA",
	2: "AMOUNT",
	3: "MARKET_VALUE",
}

var GetAccountBalancesRequest_SortField_value = map[string]int32{
	"NONE":         0,
	"ALPHA":        1,
	"AMOUNT":       2,
	"MARKET_VALUE": 3,
}

func (x GetAccountBalancesRequest_SortField) String() string {
	return proto.EnumName(GetAccountBalancesRequest_SortField_name, int32(x))
}

func (GetAccountBalancesRequest_SortField) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_acfa679eff1c5edb, []int{3, 0}
}

type GetAccountBalancesRequest_Option int32

const (
	GetAccountBalancesRequest_EOS_INCLUDE_STAKED GetAccountBalancesRequest_Option = 0
)

var GetAccountBalancesRequest_Option_name = map[int32]string{
	0: "EOS_INCLUDE_STAKED",
}

var GetAccountBalancesRequest_Option_value = map[string]int32{
	"EOS_INCLUDE_STAKED": 0,
}

func (x GetAccountBalancesRequest_Option) String() string {
	return proto.EnumName(GetAccountBalancesRequest_Option_name, int32(x))
}

func (GetAccountBalancesRequest_Option) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_acfa679eff1c5edb, []int{3, 1}
}

// You can sort by either: Account alphanumerically, Token Amount, market value of tokens
type GetTokenBalancesRequest_SortField int32

const (
	GetTokenBalancesRequest_NONE         GetTokenBalancesRequest_SortField = 0
	GetTokenBalancesRequest_ALPHA        GetTokenBalancesRequest_SortField = 1
	GetTokenBalancesRequest_AMOUNT       GetTokenBalancesRequest_SortField = 2
	GetTokenBalancesRequest_MARKET_VALUE GetTokenBalancesRequest_SortField = 3
)

var GetTokenBalancesRequest_SortField_name = map[int32]string{
	0: "NONE",
	1: "ALPHA",
	2: "AMOUNT",
	3: "MARKET_VALUE",
}

var GetTokenBalancesRequest_SortField_value = map[string]int32{
	"NONE":         0,
	"ALPHA":        1,
	"AMOUNT":       2,
	"MARKET_VALUE": 3,
}

func (x GetTokenBalancesRequest_SortField) String() string {
	return proto.EnumName(GetTokenBalancesRequest_SortField_name, int32(x))
}

func (GetTokenBalancesRequest_SortField) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_acfa679eff1c5edb, []int{5, 0}
}

type GetTokenBalancesRequest_Option int32

const (
	GetTokenBalancesRequest_EOS_INCLUDE_STAKED GetTokenBalancesRequest_Option = 0
)

var GetTokenBalancesRequest_Option_name = map[int32]string{
	0: "EOS_INCLUDE_STAKED",
}

var GetTokenBalancesRequest_Option_value = map[string]int32{
	"EOS_INCLUDE_STAKED": 0,
}

func (x GetTokenBalancesRequest_Option) String() string {
	return proto.EnumName(GetTokenBalancesRequest_Option_name, int32(x))
}

func (GetTokenBalancesRequest_Option) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_acfa679eff1c5edb, []int{5, 1}
}

type GetTokensRequest struct {
	Limit                uint32                     `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	SortOrder            SortOrder                  `protobuf:"varint,2,opt,name=sort_order,json=sortOrder,proto3,enum=dfuse.eosio.tokenmeta.v1.SortOrder" json:"sort_order,omitempty"`
	SortField            GetTokensRequest_SortField `protobuf:"varint,3,opt,name=sort_field,json=sortField,proto3,enum=dfuse.eosio.tokenmeta.v1.GetTokensRequest_SortField" json:"sort_field,omitempty"`
	SecondarySortOrder   SortOrder                  `protobuf:"varint,8,opt,name=secondary_sort_order,json=secondarySortOrder,proto3,enum=dfuse.eosio.tokenmeta.v1.SortOrder" json:"secondary_sort_order,omitempty"`
	SecondarySortField   GetTokensRequest_SortField `protobuf:"varint,9,opt,name=secondary_sort_field,json=secondarySortField,proto3,enum=dfuse.eosio.tokenmeta.v1.GetTokensRequest_SortField" json:"secondary_sort_field,omitempty"`
	FilterTokenSymbols   []string                   `protobuf:"bytes,4,rep,name=filter_token_symbols,json=filterTokenSymbols,proto3" json:"filter_token_symbols,omitempty"`
	FilterTokenContracts []string                   `protobuf:"bytes,5,rep,name=filter_token_contracts,json=filterTokenContracts,proto3" json:"filter_token_contracts,omitempty"`
	BeforeCursor         *TokenCursor               `protobuf:"bytes,6,opt,name=before_cursor,json=beforeCursor,proto3" json:"before_cursor,omitempty"`
	AfterCursor          *TokenCursor               `protobuf:"bytes,7,opt,name=after_cursor,json=afterCursor,proto3" json:"after_cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetTokensRequest) Reset()         { *m = GetTokensRequest{} }
func (m *GetTokensRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokensRequest) ProtoMessage()    {}
func (*GetTokensRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_acfa679eff1c5edb, []int{0}
}

func (m *GetTokensRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokensRequest.Unmarshal(m, b)
}
func (m *GetTokensRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokensRequest.Marshal(b, m, deterministic)
}
func (m *GetTokensRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokensRequest.Merge(m, src)
}
func (m *GetTokensRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokensRequest.Size(m)
}
func (m *GetTokensRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokensRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokensRequest proto.InternalMessageInfo

func (m *GetTokensRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetTokensRequest) GetSortOrder() SortOrder {
	if m != nil {
		return m.SortOrder
	}
	return SortOrder_ASC
}

func (m *GetTokensRequest) GetSortField() GetTokensRequest_SortField {
	if m != nil {
		return m.SortField
	}
	return GetTokensRequest_NONE
}

func (m *GetTokensRequest) GetSecondarySortOrder() SortOrder {
	if m != nil {
		return m.SecondarySortOrder
	}
	return SortOrder_ASC
}

func (m *GetTokensRequest) GetSecondarySortField() GetTokensRequest_SortField {
	if m != nil {
		return m.SecondarySortField
	}
	return GetTokensRequest_NONE
}

func (m *GetTokensRequest) GetFilterTokenSymbols() []string {
	if m != nil {
		return m.FilterTokenSymbols
	}
	return nil
}

func (m *GetTokensRequest) GetFilterTokenContracts() []string {
	if m != nil {
		return m.FilterTokenContracts
	}
	return nil
}

func (m *GetTokensRequest) GetBeforeCursor() *TokenCursor {
	if m != nil {
		return m.BeforeCursor
	}
	return nil
}

func (m *GetTokensRequest) GetAfterCursor() *TokenCursor {
	if m != nil {
		return m.AfterCursor
	}
	return nil
}

type TokensResponse struct {
	Tokens               []*Token `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	AtBlockNum           uint64   `protobuf:"varint,2,opt,name=atBlockNum,proto3" json:"atBlockNum,omitempty"`
	AtBlockId            string   `protobuf:"bytes,3,opt,name=atBlockId,proto3" json:"atBlockId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokensResponse) Reset()         { *m = TokensResponse{} }
func (m *TokensResponse) String() string { return proto.CompactTextString(m) }
func (*TokensResponse) ProtoMessage()    {}
func (*TokensResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_acfa679eff1c5edb, []int{1}
}

func (m *TokensResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokensResponse.Unmarshal(m, b)
}
func (m *TokensResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokensResponse.Marshal(b, m, deterministic)
}
func (m *TokensResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokensResponse.Merge(m, src)
}
func (m *TokensResponse) XXX_Size() int {
	return xxx_messageInfo_TokensResponse.Size(m)
}
func (m *TokensResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokensResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokensResponse proto.InternalMessageInfo

func (m *TokensResponse) GetTokens() []*Token {
	if m != nil {
		return m.Tokens
	}
	return nil
}

func (m *TokensResponse) GetAtBlockNum() uint64 {
	if m != nil {
		return m.AtBlockNum
	}
	return 0
}

func (m *TokensResponse) GetAtBlockId() string {
	if m != nil {
		return m.AtBlockId
	}
	return ""
}

type Token struct {
	Contract      string `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Symbol        string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Precision     uint32 `protobuf:"varint,3,opt,name=precision,proto3" json:"precision,omitempty"`
	Issuer        string `protobuf:"bytes,4,opt,name=issuer,proto3" json:"issuer,omitempty"`
	MaximumSupply uint64 `protobuf:"varint,5,opt,name=maximum_supply,json=maximumSupply,proto3" json:"maximum_supply,omitempty"`
	TotalSupply   uint64 `protobuf:"varint,6,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`
	Holders       uint64 `protobuf:"varint,7,opt,name=holders,proto3" json:"holders,omitempty"`
	// Eventually:
	MarketCap            uint64   `protobuf:"varint,8,opt,name=market_cap,json=marketCap,proto3" json:"market_cap,omitempty"`
	Website              string   `protobuf:"bytes,9,opt,name=website,proto3" json:"website,omitempty"`
	Logo                 string   `protobuf:"bytes,10,opt,name=logo,proto3" json:"logo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_acfa679eff1c5edb, []int{2}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *Token) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Token) GetPrecision() uint32 {
	if m != nil {
		return m.Precision
	}
	return 0
}

func (m *Token) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *Token) GetMaximumSupply() uint64 {
	if m != nil {
		return m.MaximumSupply
	}
	return 0
}

func (m *Token) GetTotalSupply() uint64 {
	if m != nil {
		return m.TotalSupply
	}
	return 0
}

func (m *Token) GetHolders() uint64 {
	if m != nil {
		return m.Holders
	}
	return 0
}

func (m *Token) GetMarketCap() uint64 {
	if m != nil {
		return m.MarketCap
	}
	return 0
}

func (m *Token) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *Token) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

type GetAccountBalancesRequest struct {
	Account              string                              `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Limit                uint32                              `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SortOrder            SortOrder                           `protobuf:"varint,3,opt,name=sort_order,json=sortOrder,proto3,enum=dfuse.eosio.tokenmeta.v1.SortOrder" json:"sort_order,omitempty"`
	SortField            GetAccountBalancesRequest_SortField `protobuf:"varint,4,opt,name=sort_field,json=sortField,proto3,enum=dfuse.eosio.tokenmeta.v1.GetAccountBalancesRequest_SortField" json:"sort_field,omitempty"`
	SecondarySortOrder   SortOrder                           `protobuf:"varint,10,opt,name=secondary_sort_order,json=secondarySortOrder,proto3,enum=dfuse.eosio.tokenmeta.v1.SortOrder" json:"secondary_sort_order,omitempty"`
	SecondarySortField   GetAccountBalancesRequest_SortField `protobuf:"varint,11,opt,name=secondary_sort_field,json=secondarySortField,proto3,enum=dfuse.eosio.tokenmeta.v1.GetAccountBalancesRequest_SortField" json:"secondary_sort_field,omitempty"`
	FilterTokenContracts []string                            `protobuf:"bytes,5,rep,name=filter_token_contracts,json=filterTokenContracts,proto3" json:"filter_token_contracts,omitempty"`
	FilterTokenSymbols   []string                            `protobuf:"bytes,6,rep,name=filter_token_symbols,json=filterTokenSymbols,proto3" json:"filter_token_symbols,omitempty"`
	Options              []GetAccountBalancesRequest_Option  `protobuf:"varint,9,rep,packed,name=options,proto3,enum=dfuse.eosio.tokenmeta.v1.GetAccountBalancesRequest_Option" json:"options,omitempty"`
	BeforeCursor         *AccountBalanceCursor               `protobuf:"bytes,7,opt,name=before_cursor,json=beforeCursor,proto3" json:"before_cursor,omitempty"`
	AfterCursor          *AccountBalanceCursor               `protobuf:"bytes,8,opt,name=after_cursor,json=afterCursor,proto3" json:"after_cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *GetAccountBalancesRequest) Reset()         { *m = GetAccountBalancesRequest{} }
func (m *GetAccountBalancesRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountBalancesRequest) ProtoMessage()    {}
func (*GetAccountBalancesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_acfa679eff1c5edb, []int{3}
}

func (m *GetAccountBalancesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountBalancesRequest.Unmarshal(m, b)
}
func (m *GetAccountBalancesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountBalancesRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountBalancesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountBalancesRequest.Merge(m, src)
}
func (m *GetAccountBalancesRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountBalancesRequest.Size(m)
}
func (m *GetAccountBalancesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountBalancesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountBalancesRequest proto.InternalMessageInfo

func (m *GetAccountBalancesRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *GetAccountBalancesRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetAccountBalancesRequest) GetSortOrder() SortOrder {
	if m != nil {
		return m.SortOrder
	}
	return SortOrder_ASC
}

func (m *GetAccountBalancesRequest) GetSortField() GetAccountBalancesRequest_SortField {
	if m != nil {
		return m.SortField
	}
	return GetAccountBalancesRequest_NONE
}

func (m *GetAccountBalancesRequest) GetSecondarySortOrder() SortOrder {
	if m != nil {
		return m.SecondarySortOrder
	}
	return SortOrder_ASC
}

func (m *GetAccountBalancesRequest) GetSecondarySortField() GetAccountBalancesRequest_SortField {
	if m != nil {
		return m.SecondarySortField
	}
	return GetAccountBalancesRequest_NONE
}

func (m *GetAccountBalancesRequest) GetFilterTokenContracts() []string {
	if m != nil {
		return m.FilterTokenContracts
	}
	return nil
}

func (m *GetAccountBalancesRequest) GetFilterTokenSymbols() []string {
	if m != nil {
		return m.FilterTokenSymbols
	}
	return nil
}

func (m *GetAccountBalancesRequest) GetOptions() []GetAccountBalancesRequest_Option {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *GetAccountBalancesRequest) GetBeforeCursor() *AccountBalanceCursor {
	if m != nil {
		return m.BeforeCursor
	}
	return nil
}

func (m *GetAccountBalancesRequest) GetAfterCursor() *AccountBalanceCursor {
	if m != nil {
		return m.AfterCursor
	}
	return nil
}

type AccountBalancesResponse struct {
	Balances             []*AccountBalance `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
	AtBlockNum           uint64            `protobuf:"varint,2,opt,name=atBlockNum,proto3" json:"atBlockNum,omitempty"`
	AtBlockId            string            `protobuf:"bytes,3,opt,name=atBlockId,proto3" json:"atBlockId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AccountBalancesResponse) Reset()         { *m = AccountBalancesResponse{} }
func (m *AccountBalancesResponse) String() string { return proto.CompactTextString(m) }
func (*AccountBalancesResponse) ProtoMessage()    {}
func (*AccountBalancesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_acfa679eff1c5edb, []int{4}
}

func (m *AccountBalancesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountBalancesResponse.Unmarshal(m, b)
}
func (m *AccountBalancesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountBalancesResponse.Marshal(b, m, deterministic)
}
func (m *AccountBalancesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountBalancesResponse.Merge(m, src)
}
func (m *AccountBalancesResponse) XXX_Size() int {
	return xxx_messageInfo_AccountBalancesResponse.Size(m)
}
func (m *AccountBalancesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountBalancesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountBalancesResponse proto.InternalMessageInfo

func (m *AccountBalancesResponse) GetBalances() []*AccountBalance {
	if m != nil {
		return m.Balances
	}
	return nil
}

func (m *AccountBalancesResponse) GetAtBlockNum() uint64 {
	if m != nil {
		return m.AtBlockNum
	}
	return 0
}

func (m *AccountBalancesResponse) GetAtBlockId() string {
	if m != nil {
		return m.AtBlockId
	}
	return ""
}

type GetTokenBalancesRequest struct {
	TokenContract        string                            `protobuf:"bytes,1,opt,name=token_contract,json=tokenContract,proto3" json:"token_contract,omitempty"`
	Limit                uint32                            `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SortOrder            SortOrder                         `protobuf:"varint,3,opt,name=sort_order,json=sortOrder,proto3,enum=dfuse.eosio.tokenmeta.v1.SortOrder" json:"sort_order,omitempty"`
	SortField            GetTokenBalancesRequest_SortField `protobuf:"varint,4,opt,name=sort_field,json=sortField,proto3,enum=dfuse.eosio.tokenmeta.v1.GetTokenBalancesRequest_SortField" json:"sort_field,omitempty"`
	SecondarySortOrder   SortOrder                         `protobuf:"varint,10,opt,name=secondary_sort_order,json=secondarySortOrder,proto3,enum=dfuse.eosio.tokenmeta.v1.SortOrder" json:"secondary_sort_order,omitempty"`
	SecondarySortField   GetTokenBalancesRequest_SortField `protobuf:"varint,11,opt,name=secondary_sort_field,json=secondarySortField,proto3,enum=dfuse.eosio.tokenmeta.v1.GetTokenBalancesRequest_SortField" json:"secondary_sort_field,omitempty"`
	FilterTokenSymbols   []string                          `protobuf:"bytes,5,rep,name=filter_token_symbols,json=filterTokenSymbols,proto3" json:"filter_token_symbols,omitempty"`
	FilterHolderAccounts []string                          `protobuf:"bytes,6,rep,name=filter_holder_accounts,json=filterHolderAccounts,proto3" json:"filter_holder_accounts,omitempty"`
	Options              []GetTokenBalancesRequest_Option  `protobuf:"varint,9,rep,packed,name=options,proto3,enum=dfuse.eosio.tokenmeta.v1.GetTokenBalancesRequest_Option" json:"options,omitempty"`
	BeforeCursor         *AccountBalanceCursor             `protobuf:"bytes,7,opt,name=before_cursor,json=beforeCursor,proto3" json:"before_cursor,omitempty"`
	AfterCursor          *AccountBalanceCursor             `protobuf:"bytes,8,opt,name=after_cursor,json=afterCursor,proto3" json:"after_cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *GetTokenBalancesRequest) Reset()         { *m = GetTokenBalancesRequest{} }
func (m *GetTokenBalancesRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokenBalancesRequest) ProtoMessage()    {}
func (*GetTokenBalancesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_acfa679eff1c5edb, []int{5}
}

func (m *GetTokenBalancesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenBalancesRequest.Unmarshal(m, b)
}
func (m *GetTokenBalancesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenBalancesRequest.Marshal(b, m, deterministic)
}
func (m *GetTokenBalancesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenBalancesRequest.Merge(m, src)
}
func (m *GetTokenBalancesRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokenBalancesRequest.Size(m)
}
func (m *GetTokenBalancesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenBalancesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenBalancesRequest proto.InternalMessageInfo

func (m *GetTokenBalancesRequest) GetTokenContract() string {
	if m != nil {
		return m.TokenContract
	}
	return ""
}

func (m *GetTokenBalancesRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetTokenBalancesRequest) GetSortOrder() SortOrder {
	if m != nil {
		return m.SortOrder
	}
	return SortOrder_ASC
}

func (m *GetTokenBalancesRequest) GetSortField() GetTokenBalancesRequest_SortField {
	if m != nil {
		return m.SortField
	}
	return GetTokenBalancesRequest_NONE
}

func (m *GetTokenBalancesRequest) GetSecondarySortOrder() SortOrder {
	if m != nil {
		return m.SecondarySortOrder
	}
	return SortOrder_ASC
}

func (m *GetTokenBalancesRequest) GetSecondarySortField() GetTokenBalancesRequest_SortField {
	if m != nil {
		return m.SecondarySortField
	}
	return GetTokenBalancesRequest_NONE
}

func (m *GetTokenBalancesRequest) GetFilterTokenSymbols() []string {
	if m != nil {
		return m.FilterTokenSymbols
	}
	return nil
}

func (m *GetTokenBalancesRequest) GetFilterHolderAccounts() []string {
	if m != nil {
		return m.FilterHolderAccounts
	}
	return nil
}

func (m *GetTokenBalancesRequest) GetOptions() []GetTokenBalancesRequest_Option {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *GetTokenBalancesRequest) GetBeforeCursor() *AccountBalanceCursor {
	if m != nil {
		return m.BeforeCursor
	}
	return nil
}

func (m *GetTokenBalancesRequest) GetAfterCursor() *AccountBalanceCursor {
	if m != nil {
		return m.AfterCursor
	}
	return nil
}

type TokenBalancesResponse struct {
	Tokens               []*TokenContractBalancesResponse `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	AtBlockNum           uint64                           `protobuf:"varint,2,opt,name=atBlockNum,proto3" json:"atBlockNum,omitempty"`
	AtBlockId            string                           `protobuf:"bytes,3,opt,name=atBlockId,proto3" json:"atBlockId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *TokenBalancesResponse) Reset()         { *m = TokenBalancesResponse{} }
func (m *TokenBalancesResponse) String() string { return proto.CompactTextString(m) }
func (*TokenBalancesResponse) ProtoMessage()    {}
func (*TokenBalancesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_acfa679eff1c5edb, []int{6}
}

func (m *TokenBalancesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenBalancesResponse.Unmarshal(m, b)
}
func (m *TokenBalancesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenBalancesResponse.Marshal(b, m, deterministic)
}
func (m *TokenBalancesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenBalancesResponse.Merge(m, src)
}
func (m *TokenBalancesResponse) XXX_Size() int {
	return xxx_messageInfo_TokenBalancesResponse.Size(m)
}
func (m *TokenBalancesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenBalancesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenBalancesResponse proto.InternalMessageInfo

func (m *TokenBalancesResponse) GetTokens() []*TokenContractBalancesResponse {
	if m != nil {
		return m.Tokens
	}
	return nil
}

func (m *TokenBalancesResponse) GetAtBlockNum() uint64 {
	if m != nil {
		return m.AtBlockNum
	}
	return 0
}

func (m *TokenBalancesResponse) GetAtBlockId() string {
	if m != nil {
		return m.AtBlockId
	}
	return ""
}

type TokenContractBalancesResponse struct {
	Token                *Token            `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Balances             []*AccountBalance `protobuf:"bytes,2,rep,name=balances,proto3" json:"balances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TokenContractBalancesResponse) Reset()         { *m = TokenContractBalancesResponse{} }
func (m *TokenContractBalancesResponse) String() string { return proto.CompactTextString(m) }
func (*TokenContractBalancesResponse) ProtoMessage()    {}
func (*TokenContractBalancesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_acfa679eff1c5edb, []int{7}
}

func (m *TokenContractBalancesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenContractBalancesResponse.Unmarshal(m, b)
}
func (m *TokenContractBalancesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenContractBalancesResponse.Marshal(b, m, deterministic)
}
func (m *TokenContractBalancesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenContractBalancesResponse.Merge(m, src)
}
func (m *TokenContractBalancesResponse) XXX_Size() int {
	return xxx_messageInfo_TokenContractBalancesResponse.Size(m)
}
func (m *TokenContractBalancesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenContractBalancesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenContractBalancesResponse proto.InternalMessageInfo

func (m *TokenContractBalancesResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *TokenContractBalancesResponse) GetBalances() []*AccountBalance {
	if m != nil {
		return m.Balances
	}
	return nil
}

type AccountBalance struct {
	TokenContract        string   `protobuf:"bytes,1,opt,name=token_contract,json=tokenContract,proto3" json:"token_contract,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Amount               uint64   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Precision            uint32   `protobuf:"varint,4,opt,name=precision,proto3" json:"precision,omitempty"`
	Symbol               string   `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountBalance) Reset()         { *m = AccountBalance{} }
func (m *AccountBalance) String() string { return proto.CompactTextString(m) }
func (*AccountBalance) ProtoMessage()    {}
func (*AccountBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_acfa679eff1c5edb, []int{8}
}

func (m *AccountBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountBalance.Unmarshal(m, b)
}
func (m *AccountBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountBalance.Marshal(b, m, deterministic)
}
func (m *AccountBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountBalance.Merge(m, src)
}
func (m *AccountBalance) XXX_Size() int {
	return xxx_messageInfo_AccountBalance.Size(m)
}
func (m *AccountBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountBalance.DiscardUnknown(m)
}

var xxx_messageInfo_AccountBalance proto.InternalMessageInfo

func (m *AccountBalance) GetTokenContract() string {
	if m != nil {
		return m.TokenContract
	}
	return ""
}

func (m *AccountBalance) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *AccountBalance) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *AccountBalance) GetPrecision() uint32 {
	if m != nil {
		return m.Precision
	}
	return 0
}

func (m *AccountBalance) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type TransactionCursor struct {
	Ver                  int32    `protobuf:"varint,1,opt,name=ver,proto3" json:"ver,omitempty"`
	TransactionIndex     uint32   `protobuf:"varint,2,opt,name=transactionIndex,proto3" json:"transactionIndex,omitempty"`
	TransactionHash      string   `protobuf:"bytes,3,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionCursor) Reset()         { *m = TransactionCursor{} }
func (m *TransactionCursor) String() string { return proto.CompactTextString(m) }
func (*TransactionCursor) ProtoMessage()    {}
func (*TransactionCursor) Descriptor() ([]byte, []int) {
	return fileDescriptor_acfa679eff1c5edb, []int{9}
}

func (m *TransactionCursor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionCursor.Unmarshal(m, b)
}
func (m *TransactionCursor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionCursor.Marshal(b, m, deterministic)
}
func (m *TransactionCursor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionCursor.Merge(m, src)
}
func (m *TransactionCursor) XXX_Size() int {
	return xxx_messageInfo_TransactionCursor.Size(m)
}
func (m *TransactionCursor) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionCursor.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionCursor proto.InternalMessageInfo

func (m *TransactionCursor) GetVer() int32 {
	if m != nil {
		return m.Ver
	}
	return 0
}

func (m *TransactionCursor) GetTransactionIndex() uint32 {
	if m != nil {
		return m.TransactionIndex
	}
	return 0
}

func (m *TransactionCursor) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

type TokenCursor struct {
	Ver                  int32    `protobuf:"varint,1,opt,name=ver,proto3" json:"ver,omitempty"`
	Contract             string   `protobuf:"bytes,2,opt,name=contract,proto3" json:"contract,omitempty"`
	Symbol               string   `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenCursor) Reset()         { *m = TokenCursor{} }
func (m *TokenCursor) String() string { return proto.CompactTextString(m) }
func (*TokenCursor) ProtoMessage()    {}
func (*TokenCursor) Descriptor() ([]byte, []int) {
	return fileDescriptor_acfa679eff1c5edb, []int{10}
}

func (m *TokenCursor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenCursor.Unmarshal(m, b)
}
func (m *TokenCursor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenCursor.Marshal(b, m, deterministic)
}
func (m *TokenCursor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenCursor.Merge(m, src)
}
func (m *TokenCursor) XXX_Size() int {
	return xxx_messageInfo_TokenCursor.Size(m)
}
func (m *TokenCursor) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenCursor.DiscardUnknown(m)
}

var xxx_messageInfo_TokenCursor proto.InternalMessageInfo

func (m *TokenCursor) GetVer() int32 {
	if m != nil {
		return m.Ver
	}
	return 0
}

func (m *TokenCursor) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *TokenCursor) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type AccountBalanceCursor struct {
	Ver                  int32    `protobuf:"varint,1,opt,name=ver,proto3" json:"ver,omitempty"`
	Contract             string   `protobuf:"bytes,2,opt,name=contract,proto3" json:"contract,omitempty"`
	Symbol               string   `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Account              string   `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountBalanceCursor) Reset()         { *m = AccountBalanceCursor{} }
func (m *AccountBalanceCursor) String() string { return proto.CompactTextString(m) }
func (*AccountBalanceCursor) ProtoMessage()    {}
func (*AccountBalanceCursor) Descriptor() ([]byte, []int) {
	return fileDescriptor_acfa679eff1c5edb, []int{11}
}

func (m *AccountBalanceCursor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountBalanceCursor.Unmarshal(m, b)
}
func (m *AccountBalanceCursor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountBalanceCursor.Marshal(b, m, deterministic)
}
func (m *AccountBalanceCursor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountBalanceCursor.Merge(m, src)
}
func (m *AccountBalanceCursor) XXX_Size() int {
	return xxx_messageInfo_AccountBalanceCursor.Size(m)
}
func (m *AccountBalanceCursor) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountBalanceCursor.DiscardUnknown(m)
}

var xxx_messageInfo_AccountBalanceCursor proto.InternalMessageInfo

func (m *AccountBalanceCursor) GetVer() int32 {
	if m != nil {
		return m.Ver
	}
	return 0
}

func (m *AccountBalanceCursor) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *AccountBalanceCursor) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *AccountBalanceCursor) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func init() {
	proto.RegisterEnum("dfuse.eosio.tokenmeta.v1.SortOrder", SortOrder_name, SortOrder_value)
	proto.RegisterEnum("dfuse.eosio.tokenmeta.v1.GetTokensRequest_SortField", GetTokensRequest_SortField_name, GetTokensRequest_SortField_value)
	proto.RegisterEnum("dfuse.eosio.tokenmeta.v1.GetAccountBalancesRequest_SortField", GetAccountBalancesRequest_SortField_name, GetAccountBalancesRequest_SortField_value)
	proto.RegisterEnum("dfuse.eosio.tokenmeta.v1.GetAccountBalancesRequest_Option", GetAccountBalancesRequest_Option_name, GetAccountBalancesRequest_Option_value)
	proto.RegisterEnum("dfuse.eosio.tokenmeta.v1.GetTokenBalancesRequest_SortField", GetTokenBalancesRequest_SortField_name, GetTokenBalancesRequest_SortField_value)
	proto.RegisterEnum("dfuse.eosio.tokenmeta.v1.GetTokenBalancesRequest_Option", GetTokenBalancesRequest_Option_name, GetTokenBalancesRequest_Option_value)
	proto.RegisterType((*GetTokensRequest)(nil), "dfuse.eosio.tokenmeta.v1.GetTokensRequest")
	proto.RegisterType((*TokensResponse)(nil), "dfuse.eosio.tokenmeta.v1.TokensResponse")
	proto.RegisterType((*Token)(nil), "dfuse.eosio.tokenmeta.v1.Token")
	proto.RegisterType((*GetAccountBalancesRequest)(nil), "dfuse.eosio.tokenmeta.v1.GetAccountBalancesRequest")
	proto.RegisterType((*AccountBalancesResponse)(nil), "dfuse.eosio.tokenmeta.v1.AccountBalancesResponse")
	proto.RegisterType((*GetTokenBalancesRequest)(nil), "dfuse.eosio.tokenmeta.v1.GetTokenBalancesRequest")
	proto.RegisterType((*TokenBalancesResponse)(nil), "dfuse.eosio.tokenmeta.v1.TokenBalancesResponse")
	proto.RegisterType((*TokenContractBalancesResponse)(nil), "dfuse.eosio.tokenmeta.v1.TokenContractBalancesResponse")
	proto.RegisterType((*AccountBalance)(nil), "dfuse.eosio.tokenmeta.v1.AccountBalance")
	proto.RegisterType((*TransactionCursor)(nil), "dfuse.eosio.tokenmeta.v1.TransactionCursor")
	proto.RegisterType((*TokenCursor)(nil), "dfuse.eosio.tokenmeta.v1.TokenCursor")
	proto.RegisterType((*AccountBalanceCursor)(nil), "dfuse.eosio.tokenmeta.v1.AccountBalanceCursor")
}

func init() {
	proto.RegisterFile("dfuse/eosio/tokenmeta/v1/tokenmeta.proto", fileDescriptor_acfa679eff1c5edb)
}

var fileDescriptor_acfa679eff1c5edb = []byte{
	// 1155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x98, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xc7, 0xeb, 0x38, 0x1f, 0xf5, 0x49, 0x1b, 0xcc, 0xa8, 0x74, 0x4d, 0xc5, 0x2e, 0x21, 0xa8,
	0x52, 0x54, 0x89, 0x84, 0x76, 0x17, 0x2d, 0x62, 0xb5, 0x48, 0x69, 0x1a, 0xda, 0xb2, 0x6d, 0xb3,
	0xd8, 0x29, 0x17, 0x2b, 0x24, 0xcb, 0x71, 0x26, 0x5b, 0xab, 0x71, 0x26, 0x78, 0x26, 0x65, 0x2b,
	0xb8, 0xe2, 0x86, 0x97, 0x00, 0x21, 0x71, 0xc1, 0x5b, 0xf0, 0x36, 0xbc, 0x06, 0x12, 0xca, 0xcc,
	0x38, 0x89, 0xd3, 0xb8, 0xf9, 0x68, 0x11, 0x37, 0x7b, 0x37, 0xe7, 0xcc, 0x9c, 0xff, 0x9c, 0xf9,
	0xfa, 0xe5, 0xc4, 0x50, 0x6c, 0xb5, 0xfb, 0x14, 0x97, 0x31, 0xa1, 0x1e, 0x29, 0x33, 0x72, 0x89,
	0xbb, 0x3e, 0x66, 0x4e, 0xf9, 0x6a, 0x77, 0x64, 0x94, 0x7a, 0x01, 0x61, 0x04, 0x19, 0x7c, 0x64,
	0x89, 0x8f, 0x2c, 0x8d, 0x3a, 0xaf, 0x76, 0x0b, 0x7f, 0xa5, 0x40, 0x3f, 0xc4, 0xac, 0x31, 0xf0,
	0x51, 0x13, 0x7f, 0xdf, 0xc7, 0x94, 0xa1, 0x0d, 0x48, 0x75, 0x3c, 0xdf, 0x63, 0x86, 0x92, 0x57,
	0x8a, 0xeb, 0xa6, 0x30, 0xd0, 0x3e, 0x00, 0x25, 0x01, 0xb3, 0x49, 0xd0, 0xc2, 0x81, 0x91, 0xc8,
	0x2b, 0xc5, 0xdc, 0xde, 0xc7, 0xa5, 0x38, 0xe5, 0x92, 0x45, 0x02, 0x56, 0x1f, 0x0c, 0x35, 0x35,
	0x1a, 0x36, 0x91, 0x25, 0x35, 0xda, 0x1e, 0xee, 0xb4, 0x0c, 0x95, 0x6b, 0x3c, 0x89, 0xd7, 0x98,
	0xcc, 0x8c, 0x8b, 0x7e, 0x35, 0x88, 0x15, 0xa2, 0xbc, 0x89, 0xce, 0x61, 0x83, 0x62, 0x97, 0x74,
	0x5b, 0x4e, 0x70, 0x6d, 0x8f, 0xa5, 0xb8, 0x3a, 0x7f, 0x8a, 0x68, 0x28, 0x30, 0xf4, 0xa1, 0xf6,
	0x0d, 0x59, 0x91, 0xb5, 0x76, 0x87, 0xac, 0xa3, 0xf3, 0x88, 0xf4, 0x3f, 0x85, 0x8d, 0xb6, 0xd7,
	0x61, 0x38, 0xb0, 0xb9, 0x8a, 0x4d, 0xaf, 0xfd, 0x26, 0xe9, 0x50, 0x23, 0x99, 0x57, 0x8b, 0x9a,
	0x89, 0x44, 0x1f, 0x17, 0xb4, 0x44, 0x0f, 0x7a, 0x02, 0x9b, 0x91, 0x08, 0x97, 0x74, 0x59, 0xe0,
	0xb8, 0x8c, 0x1a, 0x29, 0x1e, 0xb3, 0x31, 0x16, 0x53, 0x0d, 0xfb, 0xd0, 0xd7, 0xb0, 0xde, 0xc4,
	0x6d, 0x12, 0x60, 0xdb, 0xed, 0x07, 0x94, 0x04, 0x46, 0x3a, 0xaf, 0x14, 0xb3, 0x7b, 0xdb, 0xf1,
	0x0b, 0x11, 0x02, 0x7c, 0xb0, 0xb9, 0x26, 0x62, 0x85, 0x85, 0x8e, 0x60, 0xcd, 0x69, 0x0f, 0x12,
	0x90, 0x52, 0x99, 0x45, 0xa4, 0xb2, 0x3c, 0x54, 0x18, 0x85, 0xe7, 0xa0, 0x8d, 0xb6, 0x62, 0x15,
	0x92, 0x67, 0xf5, 0xb3, 0x9a, 0xbe, 0x82, 0x34, 0x48, 0x55, 0x4e, 0x5e, 0x1e, 0x55, 0x74, 0x05,
	0x65, 0x21, 0x73, 0x54, 0x3f, 0x39, 0xa8, 0x99, 0x96, 0x9e, 0x40, 0x39, 0x80, 0xd3, 0x8a, 0xf9,
	0xa2, 0xd6, 0xb0, 0xab, 0x95, 0x97, 0xba, 0x5a, 0xf8, 0x45, 0x81, 0x5c, 0xb8, 0xd9, 0xb4, 0x47,
	0xba, 0x14, 0xa3, 0xa7, 0x90, 0xe6, 0x53, 0x53, 0x43, 0xc9, 0xab, 0xc5, 0xec, 0xde, 0x87, 0x33,
	0xb2, 0x32, 0xe5, 0x70, 0xf4, 0x08, 0xc0, 0x61, 0xfb, 0x1d, 0xe2, 0x5e, 0x9e, 0xf5, 0x7d, 0x7e,
	0xc1, 0x93, 0xe6, 0x98, 0x07, 0x7d, 0x00, 0x9a, 0xb4, 0x8e, 0xc5, 0xdd, 0xd5, 0xcc, 0x91, 0xa3,
	0xf0, 0x47, 0x02, 0x52, 0x5c, 0x0f, 0x6d, 0xc1, 0x6a, 0x78, 0x22, 0xfc, 0x05, 0x69, 0xe6, 0xd0,
	0x46, 0x9b, 0x90, 0x16, 0xe7, 0xcb, 0xf5, 0x35, 0x53, 0x5a, 0x03, 0xed, 0x5e, 0x80, 0x5d, 0x8f,
	0x7a, 0xa4, 0xcb, 0xb5, 0xd7, 0xcd, 0x91, 0x63, 0x10, 0xe5, 0x51, 0xda, 0xc7, 0x81, 0x91, 0x14,
	0x51, 0xc2, 0x42, 0xdb, 0x90, 0xf3, 0x9d, 0x37, 0x9e, 0xdf, 0xf7, 0x6d, 0xda, 0xef, 0xf5, 0x3a,
	0xd7, 0x46, 0x8a, 0x67, 0xbd, 0x2e, 0xbd, 0x16, 0x77, 0xa2, 0x8f, 0x60, 0x8d, 0x11, 0xe6, 0x74,
	0xc2, 0x41, 0x69, 0x3e, 0x28, 0xcb, 0x7d, 0x72, 0x88, 0x01, 0x99, 0x0b, 0xd2, 0x69, 0xe1, 0x80,
	0xf2, 0xb3, 0x4c, 0x9a, 0xa1, 0x89, 0x1e, 0x02, 0xf8, 0x4e, 0x70, 0x89, 0x99, 0xed, 0x3a, 0x3d,
	0xfe, 0xa6, 0x92, 0xa6, 0x26, 0x3c, 0x55, 0xa7, 0x37, 0x08, 0xfc, 0x01, 0x37, 0xa9, 0xc7, 0x30,
	0x7f, 0x18, 0x9a, 0x19, 0x9a, 0x08, 0x41, 0xb2, 0x43, 0x5e, 0x13, 0x03, 0xb8, 0x9b, 0xb7, 0x0b,
	0xff, 0xa4, 0xe1, 0xfd, 0x43, 0xcc, 0x2a, 0xae, 0x4b, 0xfa, 0x5d, 0xb6, 0xef, 0x74, 0x9c, 0xae,
	0x8b, 0x87, 0xdc, 0x31, 0x20, 0xe3, 0x88, 0x1e, 0xb9, 0x6f, 0xa1, 0x39, 0x22, 0x52, 0x22, 0x9e,
	0x48, 0xea, 0x52, 0x44, 0xfa, 0x2e, 0x42, 0xa4, 0x24, 0xd7, 0x78, 0x7e, 0xeb, 0xdb, 0x9e, 0x9e,
	0xfc, 0x62, 0x68, 0x82, 0xbb, 0xa1, 0x89, 0xc4, 0xa0, 0x29, 0x7b, 0x1f, 0xe9, 0x4f, 0x63, 0xd4,
	0x72, 0xc4, 0x89, 0x23, 0x5b, 0x3a, 0x96, 0x6c, 0x0d, 0xc8, 0x90, 0x1e, 0xf3, 0x48, 0x97, 0x1a,
	0x5a, 0x5e, 0x2d, 0xe6, 0xf6, 0xbe, 0x58, 0x66, 0x2d, 0x75, 0x2e, 0x61, 0x86, 0x52, 0xc8, 0x9a,
	0x24, 0x9f, 0xc0, 0x55, 0x29, 0x5e, 0x3b, 0x2a, 0x3c, 0x15, 0x81, 0xdf, 0x4c, 0x20, 0x70, 0x75,
	0x29, 0xcd, 0x08, 0x0b, 0xbf, 0x9c, 0xc9, 0x42, 0x80, 0x74, 0xe5, 0xb4, 0x7e, 0x7e, 0xd6, 0xd0,
	0x13, 0x48, 0x87, 0x35, 0x89, 0xc2, 0x6f, 0x2b, 0x27, 0xe7, 0x35, 0x5d, 0x2d, 0xe4, 0x21, 0x2d,
	0x96, 0x8e, 0x36, 0x01, 0xd5, 0xea, 0x96, 0x7d, 0x7c, 0x56, 0x3d, 0x39, 0x3f, 0xa8, 0xd9, 0x56,
	0xa3, 0xf2, 0xa2, 0x76, 0xa0, 0xaf, 0x14, 0x7e, 0x53, 0xe0, 0xc1, 0x8d, 0x4d, 0x93, 0xdc, 0x3c,
	0x80, 0xd5, 0xa6, 0xf4, 0x49, 0x72, 0x16, 0xe7, 0x5d, 0x8c, 0x39, 0x8c, 0xbc, 0x23, 0x44, 0x7f,
	0xce, 0xc0, 0x83, 0xf0, 0xe7, 0x73, 0x92, 0x0e, 0xdb, 0x90, 0x8b, 0x5e, 0x3e, 0x09, 0x89, 0x75,
	0x36, 0x7e, 0xeb, 0xfe, 0x43, 0x54, 0xbc, 0x9a, 0x82, 0x8a, 0x67, 0xb3, 0xcb, 0x80, 0xff, 0x13,
	0x14, 0xfe, 0xad, 0xa0, 0xb8, 0x53, 0xf2, 0x8b, 0x94, 0x32, 0xa9, 0x39, 0x4a, 0x19, 0xf1, 0x7b,
	0x63, 0x4b, 0xe2, 0x87, 0x90, 0x90, 0x7a, 0x47, 0xbc, 0x53, 0x5e, 0x3a, 0x8a, 0xcc, 0x49, 0x4c,
	0x7c, 0xbe, 0xf8, 0x4a, 0xde, 0x42, 0x22, 0x0e, 0x12, 0x7f, 0x2a, 0xf0, 0xde, 0xc4, 0x96, 0x49,
	0x44, 0xd4, 0x27, 0x4a, 0xab, 0xa7, 0xb3, 0x0a, 0x3e, 0xf9, 0x28, 0x27, 0x85, 0xee, 0xa9, 0xe4,
	0xfa, 0x55, 0x81, 0x87, 0xb7, 0xce, 0x83, 0x3e, 0x83, 0x14, 0x9f, 0x89, 0xa3, 0x62, 0x8e, 0x52,
	0x50, 0x8c, 0x8e, 0xa0, 0x30, 0xb1, 0x2c, 0x0a, 0x0b, 0xbf, 0x2b, 0x90, 0x8b, 0x76, 0xce, 0xcb,
	0xb0, 0xb1, 0x42, 0x28, 0x11, 0x2d, 0x84, 0x36, 0x21, 0xed, 0xf8, 0xbc, 0x43, 0xe5, 0x9b, 0x25,
	0xad, 0x68, 0xfd, 0x98, 0x9c, 0x52, 0x3f, 0xca, 0xaa, 0x33, 0x35, 0x5e, 0x75, 0x16, 0x7e, 0x84,
	0x77, 0x1b, 0x81, 0xd3, 0xa5, 0x8e, 0x3b, 0xb8, 0x10, 0xf2, 0xce, 0xea, 0xa0, 0x5e, 0xe1, 0x80,
	0x27, 0x96, 0x32, 0x07, 0x4d, 0xb4, 0x03, 0x3a, 0x1b, 0x0d, 0x3b, 0xee, 0xb6, 0xf0, 0x1b, 0x49,
	0xd7, 0x1b, 0x7e, 0x54, 0x84, 0x77, 0xc6, 0x7c, 0x47, 0x0e, 0xbd, 0x90, 0xe7, 0x36, 0xe9, 0x2e,
	0x58, 0x90, 0x1d, 0xfb, 0x57, 0x30, 0x65, 0xda, 0xf1, 0x3a, 0x3a, 0x11, 0x5b, 0x47, 0xab, 0x91,
	0x15, 0x5d, 0xc1, 0xc6, 0xb4, 0x27, 0x74, 0x3f, 0xea, 0xe3, 0xe7, 0x92, 0x8c, 0x9c, 0xcb, 0xce,
	0x23, 0xf1, 0x2a, 0x05, 0x75, 0x33, 0xa0, 0x56, 0xac, 0xaa, 0xbe, 0x32, 0x78, 0x9e, 0x07, 0x35,
	0xab, 0xaa, 0x2b, 0x7b, 0x7f, 0x27, 0x40, 0xe3, 0xab, 0x3d, 0xc5, 0xcc, 0x41, 0x0e, 0x68, 0xc3,
	0x3f, 0x89, 0x68, 0x67, 0xfe, 0x7f, 0x92, 0x5b, 0xc5, 0x19, 0x17, 0x78, 0x74, 0xf3, 0x7f, 0x02,
	0x74, 0xb3, 0x40, 0x42, 0x8f, 0x97, 0x28, 0xa7, 0xb6, 0x76, 0xe7, 0xbd, 0xfb, 0xa3, 0xd9, 0xaf,
	0x46, 0x5f, 0x15, 0x86, 0x73, 0xef, 0x2e, 0xcc, 0xe8, 0xad, 0xf2, 0x8c, 0xe5, 0x4e, 0xce, 0xbb,
	0x7f, 0xfc, 0xea, 0xf0, 0xb5, 0xc7, 0x2e, 0xfa, 0xcd, 0x92, 0x4b, 0xfc, 0x32, 0x0f, 0xfe, 0xc4,
	0x23, 0xb2, 0x21, 0x3e, 0x94, 0xf4, 0x9a, 0xe5, 0xb8, 0xef, 0x26, 0xcf, 0x7a, 0xcd, 0xa1, 0xd9,
	0x4c, 0xf3, 0x4f, 0x27, 0x8f, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x82, 0x39, 0xb9, 0xbd, 0x66,
	0x11, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TokenMetaClient is the client API for TokenMeta service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TokenMetaClient interface {
	GetTokens(ctx context.Context, in *GetTokensRequest, opts ...grpc.CallOption) (*TokensResponse, error)
	GetAccountBalances(ctx context.Context, in *GetAccountBalancesRequest, opts ...grpc.CallOption) (*AccountBalancesResponse, error)
	GetTokenBalances(ctx context.Context, in *GetTokenBalancesRequest, opts ...grpc.CallOption) (*TokenBalancesResponse, error)
}

type tokenMetaClient struct {
	cc *grpc.ClientConn
}

func NewTokenMetaClient(cc *grpc.ClientConn) TokenMetaClient {
	return &tokenMetaClient{cc}
}

func (c *tokenMetaClient) GetTokens(ctx context.Context, in *GetTokensRequest, opts ...grpc.CallOption) (*TokensResponse, error) {
	out := new(TokensResponse)
	err := c.cc.Invoke(ctx, "/dfuse.eosio.tokenmeta.v1.TokenMeta/GetTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenMetaClient) GetAccountBalances(ctx context.Context, in *GetAccountBalancesRequest, opts ...grpc.CallOption) (*AccountBalancesResponse, error) {
	out := new(AccountBalancesResponse)
	err := c.cc.Invoke(ctx, "/dfuse.eosio.tokenmeta.v1.TokenMeta/GetAccountBalances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenMetaClient) GetTokenBalances(ctx context.Context, in *GetTokenBalancesRequest, opts ...grpc.CallOption) (*TokenBalancesResponse, error) {
	out := new(TokenBalancesResponse)
	err := c.cc.Invoke(ctx, "/dfuse.eosio.tokenmeta.v1.TokenMeta/GetTokenBalances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenMetaServer is the server API for TokenMeta service.
type TokenMetaServer interface {
	GetTokens(context.Context, *GetTokensRequest) (*TokensResponse, error)
	GetAccountBalances(context.Context, *GetAccountBalancesRequest) (*AccountBalancesResponse, error)
	GetTokenBalances(context.Context, *GetTokenBalancesRequest) (*TokenBalancesResponse, error)
}

// UnimplementedTokenMetaServer can be embedded to have forward compatible implementations.
type UnimplementedTokenMetaServer struct {
}

func (*UnimplementedTokenMetaServer) GetTokens(ctx context.Context, req *GetTokensRequest) (*TokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTokens not implemented")
}
func (*UnimplementedTokenMetaServer) GetAccountBalances(ctx context.Context, req *GetAccountBalancesRequest) (*AccountBalancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountBalances not implemented")
}
func (*UnimplementedTokenMetaServer) GetTokenBalances(ctx context.Context, req *GetTokenBalancesRequest) (*TokenBalancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTokenBalances not implemented")
}

func RegisterTokenMetaServer(s *grpc.Server, srv TokenMetaServer) {
	s.RegisterService(&_TokenMeta_serviceDesc, srv)
}

func _TokenMeta_GetTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenMetaServer).GetTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dfuse.eosio.tokenmeta.v1.TokenMeta/GetTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenMetaServer).GetTokens(ctx, req.(*GetTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenMeta_GetAccountBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenMetaServer).GetAccountBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dfuse.eosio.tokenmeta.v1.TokenMeta/GetAccountBalances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenMetaServer).GetAccountBalances(ctx, req.(*GetAccountBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenMeta_GetTokenBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenMetaServer).GetTokenBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dfuse.eosio.tokenmeta.v1.TokenMeta/GetTokenBalances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenMetaServer).GetTokenBalances(ctx, req.(*GetTokenBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TokenMeta_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dfuse.eosio.tokenmeta.v1.TokenMeta",
	HandlerType: (*TokenMetaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTokens",
			Handler:    _TokenMeta_GetTokens_Handler,
		},
		{
			MethodName: "GetAccountBalances",
			Handler:    _TokenMeta_GetAccountBalances_Handler,
		},
		{
			MethodName: "GetTokenBalances",
			Handler:    _TokenMeta_GetTokenBalances_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dfuse/eosio/tokenmeta/v1/tokenmeta.proto",
}
