// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dfuse/eosio/fluxdb/v1/fluxdb.proto

package pbfluxdb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetABIRequest struct {
	Contract             string   `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	BlockNum             uint64   `protobuf:"varint,2,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	ToJson               bool     `protobuf:"varint,3,opt,name=to_json,json=toJson,proto3" json:"to_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetABIRequest) Reset()         { *m = GetABIRequest{} }
func (m *GetABIRequest) String() string { return proto.CompactTextString(m) }
func (*GetABIRequest) ProtoMessage()    {}
func (*GetABIRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6353f7395e2f3f49, []int{0}
}

func (m *GetABIRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetABIRequest.Unmarshal(m, b)
}
func (m *GetABIRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetABIRequest.Marshal(b, m, deterministic)
}
func (m *GetABIRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetABIRequest.Merge(m, src)
}
func (m *GetABIRequest) XXX_Size() int {
	return xxx_messageInfo_GetABIRequest.Size(m)
}
func (m *GetABIRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetABIRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetABIRequest proto.InternalMessageInfo

func (m *GetABIRequest) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *GetABIRequest) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *GetABIRequest) GetToJson() bool {
	if m != nil {
		return m.ToJson
	}
	return false
}

type GetABIResponse struct {
	BlockNum             uint64   `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	RawAbi               []byte   `protobuf:"bytes,2,opt,name=raw_abi,json=rawAbi,proto3" json:"raw_abi,omitempty"`
	JsonAbi              string   `protobuf:"bytes,3,opt,name=json_abi,json=jsonAbi,proto3" json:"json_abi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetABIResponse) Reset()         { *m = GetABIResponse{} }
func (m *GetABIResponse) String() string { return proto.CompactTextString(m) }
func (*GetABIResponse) ProtoMessage()    {}
func (*GetABIResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6353f7395e2f3f49, []int{1}
}

func (m *GetABIResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetABIResponse.Unmarshal(m, b)
}
func (m *GetABIResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetABIResponse.Marshal(b, m, deterministic)
}
func (m *GetABIResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetABIResponse.Merge(m, src)
}
func (m *GetABIResponse) XXX_Size() int {
	return xxx_messageInfo_GetABIResponse.Size(m)
}
func (m *GetABIResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetABIResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetABIResponse proto.InternalMessageInfo

func (m *GetABIResponse) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *GetABIResponse) GetRawAbi() []byte {
	if m != nil {
		return m.RawAbi
	}
	return nil
}

func (m *GetABIResponse) GetJsonAbi() string {
	if m != nil {
		return m.JsonAbi
	}
	return ""
}

type GetKeyAccountsRequest struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	BlockNum             uint64   `protobuf:"varint,2,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKeyAccountsRequest) Reset()         { *m = GetKeyAccountsRequest{} }
func (m *GetKeyAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*GetKeyAccountsRequest) ProtoMessage()    {}
func (*GetKeyAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6353f7395e2f3f49, []int{2}
}

func (m *GetKeyAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKeyAccountsRequest.Unmarshal(m, b)
}
func (m *GetKeyAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKeyAccountsRequest.Marshal(b, m, deterministic)
}
func (m *GetKeyAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKeyAccountsRequest.Merge(m, src)
}
func (m *GetKeyAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_GetKeyAccountsRequest.Size(m)
}
func (m *GetKeyAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKeyAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetKeyAccountsRequest proto.InternalMessageInfo

func (m *GetKeyAccountsRequest) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *GetKeyAccountsRequest) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

type GetKeyAccountsResponse struct {
	BlockNum             uint64   `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	Accounts             []string `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKeyAccountsResponse) Reset()         { *m = GetKeyAccountsResponse{} }
func (m *GetKeyAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*GetKeyAccountsResponse) ProtoMessage()    {}
func (*GetKeyAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6353f7395e2f3f49, []int{3}
}

func (m *GetKeyAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKeyAccountsResponse.Unmarshal(m, b)
}
func (m *GetKeyAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKeyAccountsResponse.Marshal(b, m, deterministic)
}
func (m *GetKeyAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKeyAccountsResponse.Merge(m, src)
}
func (m *GetKeyAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_GetKeyAccountsResponse.Size(m)
}
func (m *GetKeyAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKeyAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetKeyAccountsResponse proto.InternalMessageInfo

func (m *GetKeyAccountsResponse) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *GetKeyAccountsResponse) GetAccounts() []string {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type GetPermissionLinksRequest struct {
	BlockNum             uint64   `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPermissionLinksRequest) Reset()         { *m = GetPermissionLinksRequest{} }
func (m *GetPermissionLinksRequest) String() string { return proto.CompactTextString(m) }
func (*GetPermissionLinksRequest) ProtoMessage()    {}
func (*GetPermissionLinksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6353f7395e2f3f49, []int{4}
}

func (m *GetPermissionLinksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPermissionLinksRequest.Unmarshal(m, b)
}
func (m *GetPermissionLinksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPermissionLinksRequest.Marshal(b, m, deterministic)
}
func (m *GetPermissionLinksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPermissionLinksRequest.Merge(m, src)
}
func (m *GetPermissionLinksRequest) XXX_Size() int {
	return xxx_messageInfo_GetPermissionLinksRequest.Size(m)
}
func (m *GetPermissionLinksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPermissionLinksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPermissionLinksRequest proto.InternalMessageInfo

func (m *GetPermissionLinksRequest) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *GetPermissionLinksRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type GetPermissionLinksResponse struct {
	UpToBlockId              string              `protobuf:"bytes,1,opt,name=up_to_block_id,json=upToBlockId,proto3" json:"up_to_block_id,omitempty"`
	UpToBlockNum             uint64              `protobuf:"varint,2,opt,name=up_to_block_num,json=upToBlockNum,proto3" json:"up_to_block_num,omitempty"`
	LastIrreversibleBlockId  string              `protobuf:"bytes,3,opt,name=last_irreversible_block_id,json=lastIrreversibleBlockId,proto3" json:"last_irreversible_block_id,omitempty"`
	LastIrreversibleBlockNum uint64              `protobuf:"varint,4,opt,name=last_irreversible_block_num,json=lastIrreversibleBlockNum,proto3" json:"last_irreversible_block_num,omitempty"`
	Permissions              []*LinkedPermission `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}            `json:"-"`
	XXX_unrecognized         []byte              `json:"-"`
	XXX_sizecache            int32               `json:"-"`
}

func (m *GetPermissionLinksResponse) Reset()         { *m = GetPermissionLinksResponse{} }
func (m *GetPermissionLinksResponse) String() string { return proto.CompactTextString(m) }
func (*GetPermissionLinksResponse) ProtoMessage()    {}
func (*GetPermissionLinksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6353f7395e2f3f49, []int{5}
}

func (m *GetPermissionLinksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPermissionLinksResponse.Unmarshal(m, b)
}
func (m *GetPermissionLinksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPermissionLinksResponse.Marshal(b, m, deterministic)
}
func (m *GetPermissionLinksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPermissionLinksResponse.Merge(m, src)
}
func (m *GetPermissionLinksResponse) XXX_Size() int {
	return xxx_messageInfo_GetPermissionLinksResponse.Size(m)
}
func (m *GetPermissionLinksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPermissionLinksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPermissionLinksResponse proto.InternalMessageInfo

func (m *GetPermissionLinksResponse) GetUpToBlockId() string {
	if m != nil {
		return m.UpToBlockId
	}
	return ""
}

func (m *GetPermissionLinksResponse) GetUpToBlockNum() uint64 {
	if m != nil {
		return m.UpToBlockNum
	}
	return 0
}

func (m *GetPermissionLinksResponse) GetLastIrreversibleBlockId() string {
	if m != nil {
		return m.LastIrreversibleBlockId
	}
	return ""
}

func (m *GetPermissionLinksResponse) GetLastIrreversibleBlockNum() uint64 {
	if m != nil {
		return m.LastIrreversibleBlockNum
	}
	return 0
}

func (m *GetPermissionLinksResponse) GetPermissions() []*LinkedPermission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type LinkedPermission struct {
	Contract             string   `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Action               string   `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	PermissionName       string   `protobuf:"bytes,3,opt,name=permission_name,json=permissionName,proto3" json:"permission_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkedPermission) Reset()         { *m = LinkedPermission{} }
func (m *LinkedPermission) String() string { return proto.CompactTextString(m) }
func (*LinkedPermission) ProtoMessage()    {}
func (*LinkedPermission) Descriptor() ([]byte, []int) {
	return fileDescriptor_6353f7395e2f3f49, []int{6}
}

func (m *LinkedPermission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkedPermission.Unmarshal(m, b)
}
func (m *LinkedPermission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkedPermission.Marshal(b, m, deterministic)
}
func (m *LinkedPermission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkedPermission.Merge(m, src)
}
func (m *LinkedPermission) XXX_Size() int {
	return xxx_messageInfo_LinkedPermission.Size(m)
}
func (m *LinkedPermission) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkedPermission.DiscardUnknown(m)
}

var xxx_messageInfo_LinkedPermission proto.InternalMessageInfo

func (m *LinkedPermission) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *LinkedPermission) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *LinkedPermission) GetPermissionName() string {
	if m != nil {
		return m.PermissionName
	}
	return ""
}

type GetTableRowsRequest struct {
	BlockNum             uint64   `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	KeyType              string   `protobuf:"bytes,2,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	ToJson               bool     `protobuf:"varint,3,opt,name=to_json,json=toJson,proto3" json:"to_json,omitempty"`
	WithAbi              bool     `protobuf:"varint,4,opt,name=with_abi,json=withAbi,proto3" json:"with_abi,omitempty"`
	WithBlockNum         bool     `protobuf:"varint,5,opt,name=with_block_num,json=withBlockNum,proto3" json:"with_block_num,omitempty"`
	IrreversibleOnly     bool     `protobuf:"varint,6,opt,name=irreversible_only,json=irreversibleOnly,proto3" json:"irreversible_only,omitempty"`
	Account              string   `protobuf:"bytes,7,opt,name=account,proto3" json:"account,omitempty"`
	Table                string   `protobuf:"bytes,8,opt,name=table,proto3" json:"table,omitempty"`
	Scope                string   `protobuf:"bytes,9,opt,name=scope,proto3" json:"scope,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTableRowsRequest) Reset()         { *m = GetTableRowsRequest{} }
func (m *GetTableRowsRequest) String() string { return proto.CompactTextString(m) }
func (*GetTableRowsRequest) ProtoMessage()    {}
func (*GetTableRowsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6353f7395e2f3f49, []int{7}
}

func (m *GetTableRowsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTableRowsRequest.Unmarshal(m, b)
}
func (m *GetTableRowsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTableRowsRequest.Marshal(b, m, deterministic)
}
func (m *GetTableRowsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTableRowsRequest.Merge(m, src)
}
func (m *GetTableRowsRequest) XXX_Size() int {
	return xxx_messageInfo_GetTableRowsRequest.Size(m)
}
func (m *GetTableRowsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTableRowsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTableRowsRequest proto.InternalMessageInfo

func (m *GetTableRowsRequest) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *GetTableRowsRequest) GetKeyType() string {
	if m != nil {
		return m.KeyType
	}
	return ""
}

func (m *GetTableRowsRequest) GetToJson() bool {
	if m != nil {
		return m.ToJson
	}
	return false
}

func (m *GetTableRowsRequest) GetWithAbi() bool {
	if m != nil {
		return m.WithAbi
	}
	return false
}

func (m *GetTableRowsRequest) GetWithBlockNum() bool {
	if m != nil {
		return m.WithBlockNum
	}
	return false
}

func (m *GetTableRowsRequest) GetIrreversibleOnly() bool {
	if m != nil {
		return m.IrreversibleOnly
	}
	return false
}

func (m *GetTableRowsRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *GetTableRowsRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *GetTableRowsRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

type TableRowResponse struct {
	Key         string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data        []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Payer       string `protobuf:"bytes,3,opt,name=payer,proto3" json:"payer,omitempty"`
	BlockNumber uint64 `protobuf:"varint,4,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	// currently this is repeated per TableRowResponse
	UpToBlockId              string   `protobuf:"bytes,10,opt,name=up_to_block_id,json=upToBlockId,proto3" json:"up_to_block_id,omitempty"`
	UpToBlockNum             uint64   `protobuf:"varint,11,opt,name=up_to_block_num,json=upToBlockNum,proto3" json:"up_to_block_num,omitempty"`
	LastIrreversibleBlockId  string   `protobuf:"bytes,12,opt,name=last_irreversible_block_id,json=lastIrreversibleBlockId,proto3" json:"last_irreversible_block_id,omitempty"`
	LastIrreversibleBlockNum uint64   `protobuf:"varint,13,opt,name=last_irreversible_block_num,json=lastIrreversibleBlockNum,proto3" json:"last_irreversible_block_num,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *TableRowResponse) Reset()         { *m = TableRowResponse{} }
func (m *TableRowResponse) String() string { return proto.CompactTextString(m) }
func (*TableRowResponse) ProtoMessage()    {}
func (*TableRowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6353f7395e2f3f49, []int{8}
}

func (m *TableRowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableRowResponse.Unmarshal(m, b)
}
func (m *TableRowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableRowResponse.Marshal(b, m, deterministic)
}
func (m *TableRowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableRowResponse.Merge(m, src)
}
func (m *TableRowResponse) XXX_Size() int {
	return xxx_messageInfo_TableRowResponse.Size(m)
}
func (m *TableRowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TableRowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TableRowResponse proto.InternalMessageInfo

func (m *TableRowResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *TableRowResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *TableRowResponse) GetPayer() string {
	if m != nil {
		return m.Payer
	}
	return ""
}

func (m *TableRowResponse) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *TableRowResponse) GetUpToBlockId() string {
	if m != nil {
		return m.UpToBlockId
	}
	return ""
}

func (m *TableRowResponse) GetUpToBlockNum() uint64 {
	if m != nil {
		return m.UpToBlockNum
	}
	return 0
}

func (m *TableRowResponse) GetLastIrreversibleBlockId() string {
	if m != nil {
		return m.LastIrreversibleBlockId
	}
	return ""
}

func (m *TableRowResponse) GetLastIrreversibleBlockNum() uint64 {
	if m != nil {
		return m.LastIrreversibleBlockNum
	}
	return 0
}

type GetTableRowRequest struct {
	BlockNum             uint64   `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	KeyType              string   `protobuf:"bytes,2,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	ToJson               bool     `protobuf:"varint,3,opt,name=to_json,json=toJson,proto3" json:"to_json,omitempty"`
	WithAbi              bool     `protobuf:"varint,4,opt,name=with_abi,json=withAbi,proto3" json:"with_abi,omitempty"`
	WithBlockNum         bool     `protobuf:"varint,5,opt,name=with_block_num,json=withBlockNum,proto3" json:"with_block_num,omitempty"`
	IrreversibleOnly     bool     `protobuf:"varint,6,opt,name=irreversible_only,json=irreversibleOnly,proto3" json:"irreversible_only,omitempty"`
	Account              string   `protobuf:"bytes,7,opt,name=account,proto3" json:"account,omitempty"`
	Table                string   `protobuf:"bytes,8,opt,name=table,proto3" json:"table,omitempty"`
	Scope                string   `protobuf:"bytes,9,opt,name=scope,proto3" json:"scope,omitempty"`
	PrimaryKey           string   `protobuf:"bytes,10,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTableRowRequest) Reset()         { *m = GetTableRowRequest{} }
func (m *GetTableRowRequest) String() string { return proto.CompactTextString(m) }
func (*GetTableRowRequest) ProtoMessage()    {}
func (*GetTableRowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6353f7395e2f3f49, []int{9}
}

func (m *GetTableRowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTableRowRequest.Unmarshal(m, b)
}
func (m *GetTableRowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTableRowRequest.Marshal(b, m, deterministic)
}
func (m *GetTableRowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTableRowRequest.Merge(m, src)
}
func (m *GetTableRowRequest) XXX_Size() int {
	return xxx_messageInfo_GetTableRowRequest.Size(m)
}
func (m *GetTableRowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTableRowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTableRowRequest proto.InternalMessageInfo

func (m *GetTableRowRequest) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *GetTableRowRequest) GetKeyType() string {
	if m != nil {
		return m.KeyType
	}
	return ""
}

func (m *GetTableRowRequest) GetToJson() bool {
	if m != nil {
		return m.ToJson
	}
	return false
}

func (m *GetTableRowRequest) GetWithAbi() bool {
	if m != nil {
		return m.WithAbi
	}
	return false
}

func (m *GetTableRowRequest) GetWithBlockNum() bool {
	if m != nil {
		return m.WithBlockNum
	}
	return false
}

func (m *GetTableRowRequest) GetIrreversibleOnly() bool {
	if m != nil {
		return m.IrreversibleOnly
	}
	return false
}

func (m *GetTableRowRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *GetTableRowRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *GetTableRowRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *GetTableRowRequest) GetPrimaryKey() string {
	if m != nil {
		return m.PrimaryKey
	}
	return ""
}

func init() {
	proto.RegisterType((*GetABIRequest)(nil), "dfuse.eosio.fluxdb.v1.GetABIRequest")
	proto.RegisterType((*GetABIResponse)(nil), "dfuse.eosio.fluxdb.v1.GetABIResponse")
	proto.RegisterType((*GetKeyAccountsRequest)(nil), "dfuse.eosio.fluxdb.v1.GetKeyAccountsRequest")
	proto.RegisterType((*GetKeyAccountsResponse)(nil), "dfuse.eosio.fluxdb.v1.GetKeyAccountsResponse")
	proto.RegisterType((*GetPermissionLinksRequest)(nil), "dfuse.eosio.fluxdb.v1.GetPermissionLinksRequest")
	proto.RegisterType((*GetPermissionLinksResponse)(nil), "dfuse.eosio.fluxdb.v1.GetPermissionLinksResponse")
	proto.RegisterType((*LinkedPermission)(nil), "dfuse.eosio.fluxdb.v1.LinkedPermission")
	proto.RegisterType((*GetTableRowsRequest)(nil), "dfuse.eosio.fluxdb.v1.GetTableRowsRequest")
	proto.RegisterType((*TableRowResponse)(nil), "dfuse.eosio.fluxdb.v1.TableRowResponse")
	proto.RegisterType((*GetTableRowRequest)(nil), "dfuse.eosio.fluxdb.v1.GetTableRowRequest")
}

func init() { proto.RegisterFile("dfuse/eosio/fluxdb/v1/fluxdb.proto", fileDescriptor_6353f7395e2f3f49) }

var fileDescriptor_6353f7395e2f3f49 = []byte{
	// 795 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x56, 0x4b, 0x73, 0xe3, 0x44,
	0x10, 0x2e, 0x3f, 0xe2, 0x47, 0xdb, 0xeb, 0x35, 0x03, 0xbb, 0xab, 0x68, 0x8b, 0xc2, 0x88, 0xa4,
	0x62, 0x1e, 0xb1, 0x93, 0x70, 0x4c, 0x71, 0xb0, 0xa1, 0x70, 0x99, 0x50, 0x01, 0x44, 0xb8, 0x70,
	0x51, 0x8d, 0xe4, 0x09, 0x19, 0x2c, 0x69, 0x84, 0x34, 0x8a, 0xa3, 0xdf, 0xc1, 0x8d, 0x3f, 0xc1,
	0x19, 0x7e, 0x1d, 0x35, 0xa3, 0x91, 0x25, 0x3b, 0xb6, 0xe3, 0x14, 0xd7, 0xbd, 0x4d, 0xf7, 0x74,
	0x7f, 0xfd, 0x98, 0x7e, 0x0c, 0x18, 0xb3, 0xdb, 0x38, 0x22, 0x43, 0xc2, 0x22, 0xca, 0x86, 0xb7,
	0x6e, 0xfc, 0x30, 0xb3, 0x87, 0xf7, 0xe7, 0xea, 0x34, 0x08, 0x42, 0xc6, 0x19, 0x7a, 0x25, 0x65,
	0x06, 0x52, 0x66, 0xa0, 0x6e, 0xee, 0xcf, 0x0d, 0x0c, 0x2f, 0x26, 0x84, 0x8f, 0xc6, 0x53, 0x93,
	0xfc, 0x11, 0x93, 0x88, 0x23, 0x1d, 0x1a, 0x0e, 0xf3, 0x79, 0x88, 0x1d, 0xae, 0x95, 0x7a, 0xa5,
	0x7e, 0xd3, 0x5c, 0xd2, 0xe8, 0x2d, 0x34, 0x6d, 0x97, 0x39, 0x73, 0xcb, 0x8f, 0x3d, 0xad, 0xdc,
	0x2b, 0xf5, 0xab, 0x66, 0x43, 0x32, 0xae, 0x63, 0x0f, 0xbd, 0x81, 0x3a, 0x67, 0xd6, 0xef, 0x11,
	0xf3, 0xb5, 0x4a, 0xaf, 0xd4, 0x6f, 0x98, 0x35, 0xce, 0xbe, 0x8b, 0x98, 0x6f, 0x60, 0xe8, 0x64,
	0x26, 0xa2, 0x80, 0xf9, 0x11, 0x59, 0xc5, 0x29, 0x3d, 0xc6, 0x09, 0xf1, 0xc2, 0xc2, 0x36, 0x95,
	0x26, 0xda, 0x66, 0x2d, 0xc4, 0x8b, 0x91, 0x4d, 0xd1, 0x21, 0x34, 0x04, 0xba, 0xbc, 0xa9, 0x48,
	0xcf, 0xea, 0x82, 0x1e, 0xd9, 0xd4, 0xf8, 0x19, 0x5e, 0x4d, 0x08, 0xbf, 0x22, 0xc9, 0xc8, 0x71,
	0x58, 0xec, 0xf3, 0x28, 0x8b, 0xe6, 0x43, 0x80, 0x20, 0xb6, 0x5d, 0xea, 0x58, 0x73, 0x92, 0xa8,
	0x78, 0x9a, 0x29, 0xe7, 0x8a, 0x24, 0x3b, 0x03, 0x32, 0x7e, 0x82, 0xd7, 0xeb, 0xa0, 0xfb, 0xf8,
	0xaf, 0x43, 0x03, 0x2b, 0x05, 0xad, 0xdc, 0xab, 0x88, 0x04, 0x66, 0xb4, 0x61, 0xc2, 0xe1, 0x84,
	0xf0, 0x1f, 0x49, 0xe8, 0xd1, 0x28, 0xa2, 0xcc, 0xff, 0x9e, 0xfa, 0xf3, 0xa5, 0xaf, 0x3b, 0x51,
	0x35, 0xa8, 0x2b, 0x14, 0xe9, 0x67, 0xd3, 0xcc, 0x48, 0xe3, 0xef, 0x32, 0xe8, 0x9b, 0x40, 0x95,
	0xaf, 0x9f, 0x40, 0x27, 0x0e, 0x2c, 0xce, 0xac, 0x14, 0x9b, 0xce, 0x54, 0x16, 0x5a, 0x71, 0x70,
	0xc3, 0xc6, 0x82, 0x37, 0x9d, 0xa1, 0x63, 0x78, 0x59, 0x14, 0xca, 0xb3, 0xd1, 0x5e, 0x4a, 0x09,
	0x27, 0x2e, 0x41, 0x77, 0x71, 0xc4, 0x2d, 0x1a, 0x86, 0xe4, 0x9e, 0x84, 0x11, 0xb5, 0x5d, 0x92,
	0xe3, 0xa6, 0x6f, 0xf2, 0x46, 0x48, 0x4c, 0x0b, 0x02, 0x99, 0x8d, 0xaf, 0xe0, 0xed, 0x36, 0x65,
	0x61, 0xaf, 0x2a, 0xed, 0x69, 0x1b, 0xb5, 0x85, 0xed, 0x29, 0xb4, 0x82, 0x65, 0x88, 0x91, 0x76,
	0xd0, 0xab, 0xf4, 0x5b, 0x17, 0x27, 0x83, 0x8d, 0x55, 0x3d, 0x10, 0x29, 0x20, 0xb3, 0x3c, 0x25,
	0x66, 0x51, 0xd7, 0x60, 0xd0, 0x5d, 0x17, 0xd8, 0x59, 0xf6, 0xaf, 0xa1, 0x86, 0x1d, 0x4e, 0x99,
	0xaf, 0x52, 0xaf, 0x28, 0x74, 0x02, 0x2f, 0x73, 0x58, 0xcb, 0xc7, 0x1e, 0x51, 0x39, 0xe8, 0xe4,
	0xec, 0x6b, 0xec, 0x11, 0xe3, 0xaf, 0x32, 0xbc, 0x3f, 0x21, 0xfc, 0x06, 0xdb, 0x2e, 0x31, 0xd9,
	0x62, 0xbf, 0x17, 0x3f, 0x84, 0xc6, 0x9c, 0x24, 0x16, 0x4f, 0x02, 0x92, 0x3d, 0xf9, 0x9c, 0x24,
	0x37, 0x49, 0x40, 0xb6, 0xb6, 0x9a, 0xd0, 0x59, 0x50, 0x7e, 0x27, 0x5b, 0xa4, 0x2a, 0x6f, 0xea,
	0x82, 0x16, 0xdd, 0x73, 0x04, 0x1d, 0x79, 0x95, 0x1b, 0x3c, 0x90, 0x02, 0x6d, 0xc1, 0x5d, 0x66,
	0xf9, 0x73, 0x78, 0x6f, 0xe5, 0x7d, 0x98, 0xef, 0x26, 0x5a, 0x4d, 0x0a, 0x76, 0x8b, 0x17, 0x3f,
	0xf8, 0x6e, 0x52, 0xac, 0xc9, 0xfa, 0x4a, 0x4d, 0xa2, 0x0f, 0xe0, 0x80, 0x8b, 0x60, 0xb5, 0x86,
	0xe4, 0xa7, 0x84, 0xe0, 0x46, 0x0e, 0x0b, 0x88, 0xd6, 0x4c, 0xb9, 0x92, 0x30, 0xfe, 0x29, 0x43,
	0x37, 0xcb, 0xcc, 0xb2, 0x6a, 0xbb, 0x50, 0xc9, 0x1b, 0x56, 0x1c, 0x11, 0x82, 0xea, 0x0c, 0x73,
	0xac, 0x66, 0x82, 0x3c, 0x0b, 0xc0, 0x00, 0x27, 0x24, 0x54, 0x69, 0x4f, 0x09, 0xf4, 0x31, 0xb4,
	0x97, 0x41, 0xda, 0x24, 0x54, 0x95, 0xd5, 0xca, 0x12, 0x6b, 0x93, 0x70, 0x43, 0x53, 0xc0, 0x5e,
	0x4d, 0xd1, 0x7a, 0x76, 0x53, 0xb4, 0xff, 0x57, 0x53, 0xbc, 0xd8, 0xdd, 0x14, 0xc6, 0xbf, 0x65,
	0x40, 0x85, 0xc2, 0x7a, 0x57, 0x57, 0x79, 0x5d, 0xa1, 0x8f, 0xa0, 0x15, 0x84, 0xd4, 0xc3, 0x61,
	0x22, 0x67, 0x7f, 0xfa, 0xc0, 0xa0, 0x58, 0x57, 0x24, 0xb9, 0xf8, 0xb3, 0x0a, 0xb5, 0x6f, 0xdd,
	0xf8, 0xe1, 0x9b, 0x31, 0xfa, 0x05, 0x6a, 0xe9, 0x8a, 0x42, 0x47, 0x5b, 0x26, 0xca, 0xca, 0x92,
	0xd4, 0x8f, 0x9f, 0x90, 0x52, 0x55, 0xec, 0xc9, 0xcd, 0x57, 0xd8, 0x20, 0xe8, 0x8b, 0xed, 0x8a,
	0x8f, 0xb7, 0x97, 0x7e, 0xba, 0xa7, 0xb4, 0x32, 0x97, 0xc8, 0x62, 0x58, 0x5b, 0x04, 0xe8, 0x6c,
	0x3b, 0xc8, 0xe6, 0x45, 0xa4, 0x9f, 0x3f, 0x43, 0x43, 0x99, 0x26, 0xd0, 0x2e, 0x0e, 0x38, 0xf4,
	0xd9, 0x76, 0x88, 0xf5, 0x29, 0xa8, 0x6f, 0x1b, 0xe2, 0xeb, 0x43, 0xe1, 0xac, 0x84, 0x30, 0xb4,
	0x0a, 0x08, 0xe8, 0xd3, 0xa7, 0xad, 0x3c, 0xd7, 0xc8, 0xf8, 0xeb, 0x5f, 0x47, 0xbf, 0x51, 0x7e,
	0x17, 0xdb, 0x03, 0x87, 0x79, 0x43, 0xa9, 0x74, 0x4a, 0x99, 0x3a, 0xa4, 0x3f, 0xac, 0xc0, 0x1e,
	0x6e, 0xfc, 0x70, 0x5d, 0x06, 0x76, 0x7a, 0xb6, 0x6b, 0xf2, 0xcf, 0xf5, 0xe5, 0x7f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x06, 0xd2, 0xc1, 0x61, 0x99, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FluxDBClient is the client API for FluxDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FluxDBClient interface {
	// Replaces /v0/state/abi
	GetABI(ctx context.Context, in *GetABIRequest, opts ...grpc.CallOption) (*GetABIResponse, error)
	// Replaces /v0/state/key_accounts
	GetKeyAccounts(ctx context.Context, in *GetKeyAccountsRequest, opts ...grpc.CallOption) (*GetKeyAccountsResponse, error)
	// Replaces /v0/state/permission_links
	GetPermissionLinks(ctx context.Context, in *GetPermissionLinksRequest, opts ...grpc.CallOption) (*GetPermissionLinksResponse, error)
	// Replaces /v0/state/table
	GetTableRows(ctx context.Context, in *GetTableRowsRequest, opts ...grpc.CallOption) (FluxDB_GetTableRowsClient, error)
	//	// Replaces /v0/state/table/row
	GetTableRow(ctx context.Context, in *GetTableRowRequest, opts ...grpc.CallOption) (*TableRowResponse, error)
}

type fluxDBClient struct {
	cc *grpc.ClientConn
}

func NewFluxDBClient(cc *grpc.ClientConn) FluxDBClient {
	return &fluxDBClient{cc}
}

func (c *fluxDBClient) GetABI(ctx context.Context, in *GetABIRequest, opts ...grpc.CallOption) (*GetABIResponse, error) {
	out := new(GetABIResponse)
	err := c.cc.Invoke(ctx, "/dfuse.eosio.fluxdb.v1.FluxDB/GetABI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fluxDBClient) GetKeyAccounts(ctx context.Context, in *GetKeyAccountsRequest, opts ...grpc.CallOption) (*GetKeyAccountsResponse, error) {
	out := new(GetKeyAccountsResponse)
	err := c.cc.Invoke(ctx, "/dfuse.eosio.fluxdb.v1.FluxDB/GetKeyAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fluxDBClient) GetPermissionLinks(ctx context.Context, in *GetPermissionLinksRequest, opts ...grpc.CallOption) (*GetPermissionLinksResponse, error) {
	out := new(GetPermissionLinksResponse)
	err := c.cc.Invoke(ctx, "/dfuse.eosio.fluxdb.v1.FluxDB/GetPermissionLinks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fluxDBClient) GetTableRows(ctx context.Context, in *GetTableRowsRequest, opts ...grpc.CallOption) (FluxDB_GetTableRowsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FluxDB_serviceDesc.Streams[0], "/dfuse.eosio.fluxdb.v1.FluxDB/GetTableRows", opts...)
	if err != nil {
		return nil, err
	}
	x := &fluxDBGetTableRowsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FluxDB_GetTableRowsClient interface {
	Recv() (*TableRowResponse, error)
	grpc.ClientStream
}

type fluxDBGetTableRowsClient struct {
	grpc.ClientStream
}

func (x *fluxDBGetTableRowsClient) Recv() (*TableRowResponse, error) {
	m := new(TableRowResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fluxDBClient) GetTableRow(ctx context.Context, in *GetTableRowRequest, opts ...grpc.CallOption) (*TableRowResponse, error) {
	out := new(TableRowResponse)
	err := c.cc.Invoke(ctx, "/dfuse.eosio.fluxdb.v1.FluxDB/GetTableRow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FluxDBServer is the server API for FluxDB service.
type FluxDBServer interface {
	// Replaces /v0/state/abi
	GetABI(context.Context, *GetABIRequest) (*GetABIResponse, error)
	// Replaces /v0/state/key_accounts
	GetKeyAccounts(context.Context, *GetKeyAccountsRequest) (*GetKeyAccountsResponse, error)
	// Replaces /v0/state/permission_links
	GetPermissionLinks(context.Context, *GetPermissionLinksRequest) (*GetPermissionLinksResponse, error)
	// Replaces /v0/state/table
	GetTableRows(*GetTableRowsRequest, FluxDB_GetTableRowsServer) error
	//	// Replaces /v0/state/table/row
	GetTableRow(context.Context, *GetTableRowRequest) (*TableRowResponse, error)
}

// UnimplementedFluxDBServer can be embedded to have forward compatible implementations.
type UnimplementedFluxDBServer struct {
}

func (*UnimplementedFluxDBServer) GetABI(ctx context.Context, req *GetABIRequest) (*GetABIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetABI not implemented")
}
func (*UnimplementedFluxDBServer) GetKeyAccounts(ctx context.Context, req *GetKeyAccountsRequest) (*GetKeyAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyAccounts not implemented")
}
func (*UnimplementedFluxDBServer) GetPermissionLinks(ctx context.Context, req *GetPermissionLinksRequest) (*GetPermissionLinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPermissionLinks not implemented")
}
func (*UnimplementedFluxDBServer) GetTableRows(req *GetTableRowsRequest, srv FluxDB_GetTableRowsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetTableRows not implemented")
}
func (*UnimplementedFluxDBServer) GetTableRow(ctx context.Context, req *GetTableRowRequest) (*TableRowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTableRow not implemented")
}

func RegisterFluxDBServer(s *grpc.Server, srv FluxDBServer) {
	s.RegisterService(&_FluxDB_serviceDesc, srv)
}

func _FluxDB_GetABI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetABIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FluxDBServer).GetABI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dfuse.eosio.fluxdb.v1.FluxDB/GetABI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FluxDBServer).GetABI(ctx, req.(*GetABIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FluxDB_GetKeyAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FluxDBServer).GetKeyAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dfuse.eosio.fluxdb.v1.FluxDB/GetKeyAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FluxDBServer).GetKeyAccounts(ctx, req.(*GetKeyAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FluxDB_GetPermissionLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPermissionLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FluxDBServer).GetPermissionLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dfuse.eosio.fluxdb.v1.FluxDB/GetPermissionLinks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FluxDBServer).GetPermissionLinks(ctx, req.(*GetPermissionLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FluxDB_GetTableRows_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetTableRowsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FluxDBServer).GetTableRows(m, &fluxDBGetTableRowsServer{stream})
}

type FluxDB_GetTableRowsServer interface {
	Send(*TableRowResponse) error
	grpc.ServerStream
}

type fluxDBGetTableRowsServer struct {
	grpc.ServerStream
}

func (x *fluxDBGetTableRowsServer) Send(m *TableRowResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _FluxDB_GetTableRow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableRowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FluxDBServer).GetTableRow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dfuse.eosio.fluxdb.v1.FluxDB/GetTableRow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FluxDBServer).GetTableRow(ctx, req.(*GetTableRowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FluxDB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dfuse.eosio.fluxdb.v1.FluxDB",
	HandlerType: (*FluxDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetABI",
			Handler:    _FluxDB_GetABI_Handler,
		},
		{
			MethodName: "GetKeyAccounts",
			Handler:    _FluxDB_GetKeyAccounts_Handler,
		},
		{
			MethodName: "GetPermissionLinks",
			Handler:    _FluxDB_GetPermissionLinks_Handler,
		},
		{
			MethodName: "GetTableRow",
			Handler:    _FluxDB_GetTableRow_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTableRows",
			Handler:       _FluxDB_GetTableRows_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dfuse/eosio/fluxdb/v1/fluxdb.proto",
}
