// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dfuse/eosio/trxdb/v1/trxdb.proto

package pbtrxdb

import (
	fmt "fmt"
	v1 "github.com/dfuse-io/dfuse-eosio/pb/dfuse/eosio/codec/v1"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IndexableRow int32

const (
	IndexableRow_INDEXABLE_ROW_ACCOUNT      IndexableRow = 0
	IndexableRow_INDEXABLE_ROW_BLOCK        IndexableRow = 1
	IndexableRow_INDEXABLE_ROW_DTRX         IndexableRow = 2
	IndexableRow_INDEXABLE_ROW_IMPLICIT_TRX IndexableRow = 3
	IndexableRow_INDEXABLE_ROW_TRX          IndexableRow = 4
	IndexableRow_INDEXABLE_ROW_TRX_TRACE    IndexableRow = 5
	IndexableRow_INDEXABLE_ROW_TIMELINE     IndexableRow = 6
)

var IndexableRow_name = map[int32]string{
	0: "INDEXABLE_ROW_ACCOUNT",
	1: "INDEXABLE_ROW_BLOCK",
	2: "INDEXABLE_ROW_DTRX",
	3: "INDEXABLE_ROW_IMPLICIT_TRX",
	4: "INDEXABLE_ROW_TRX",
	5: "INDEXABLE_ROW_TRX_TRACE",
	6: "INDEXABLE_ROW_TIMELINE",
}

var IndexableRow_value = map[string]int32{
	"INDEXABLE_ROW_ACCOUNT":      0,
	"INDEXABLE_ROW_BLOCK":        1,
	"INDEXABLE_ROW_DTRX":         2,
	"INDEXABLE_ROW_IMPLICIT_TRX": 3,
	"INDEXABLE_ROW_TRX":          4,
	"INDEXABLE_ROW_TRX_TRACE":    5,
	"INDEXABLE_ROW_TIMELINE":     6,
}

func (x IndexableRow) String() string {
	return proto.EnumName(IndexableRow_name, int32(x))
}

func (IndexableRow) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_014579ff7d302fea, []int{0}
}

type ImplicitTrxRow struct {
	// Primary key to include: transaction_id and block_id
	SignedTrx            *v1.SignedTransaction `protobuf:"bytes,1,opt,name=signed_trx,json=signedTrx,proto3" json:"signed_trx,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ImplicitTrxRow) Reset()         { *m = ImplicitTrxRow{} }
func (m *ImplicitTrxRow) String() string { return proto.CompactTextString(m) }
func (*ImplicitTrxRow) ProtoMessage()    {}
func (*ImplicitTrxRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_014579ff7d302fea, []int{0}
}

func (m *ImplicitTrxRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImplicitTrxRow.Unmarshal(m, b)
}
func (m *ImplicitTrxRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImplicitTrxRow.Marshal(b, m, deterministic)
}
func (m *ImplicitTrxRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImplicitTrxRow.Merge(m, src)
}
func (m *ImplicitTrxRow) XXX_Size() int {
	return xxx_messageInfo_ImplicitTrxRow.Size(m)
}
func (m *ImplicitTrxRow) XXX_DiscardUnknown() {
	xxx_messageInfo_ImplicitTrxRow.DiscardUnknown(m)
}

var xxx_messageInfo_ImplicitTrxRow proto.InternalMessageInfo

func (m *ImplicitTrxRow) GetSignedTrx() *v1.SignedTransaction {
	if m != nil {
		return m.SignedTrx
	}
	return nil
}

func (m *ImplicitTrxRow) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TrxRow struct {
	SignedTrx            *v1.SignedTransaction  `protobuf:"bytes,1,opt,name=signed_trx,json=signedTrx,proto3" json:"signed_trx,omitempty"`
	Receipt              *v1.TransactionReceipt `protobuf:"bytes,2,opt,name=receipt,proto3" json:"receipt,omitempty"`
	PublicKeys           *v1.PublicKeys         `protobuf:"bytes,3,opt,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TrxRow) Reset()         { *m = TrxRow{} }
func (m *TrxRow) String() string { return proto.CompactTextString(m) }
func (*TrxRow) ProtoMessage()    {}
func (*TrxRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_014579ff7d302fea, []int{1}
}

func (m *TrxRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrxRow.Unmarshal(m, b)
}
func (m *TrxRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrxRow.Marshal(b, m, deterministic)
}
func (m *TrxRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrxRow.Merge(m, src)
}
func (m *TrxRow) XXX_Size() int {
	return xxx_messageInfo_TrxRow.Size(m)
}
func (m *TrxRow) XXX_DiscardUnknown() {
	xxx_messageInfo_TrxRow.DiscardUnknown(m)
}

var xxx_messageInfo_TrxRow proto.InternalMessageInfo

func (m *TrxRow) GetSignedTrx() *v1.SignedTransaction {
	if m != nil {
		return m.SignedTrx
	}
	return nil
}

func (m *TrxRow) GetReceipt() *v1.TransactionReceipt {
	if m != nil {
		return m.Receipt
	}
	return nil
}

func (m *TrxRow) GetPublicKeys() *v1.PublicKeys {
	if m != nil {
		return m.PublicKeys
	}
	return nil
}

type TrxTraceRow struct {
	TrxTrace             *v1.TransactionTrace `protobuf:"bytes,1,opt,name=trx_trace,json=trxTrace,proto3" json:"trx_trace,omitempty"`
	BlockHeader          *v1.BlockHeader      `protobuf:"bytes,2,opt,name=block_header,json=blockHeader,proto3" json:"block_header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TrxTraceRow) Reset()         { *m = TrxTraceRow{} }
func (m *TrxTraceRow) String() string { return proto.CompactTextString(m) }
func (*TrxTraceRow) ProtoMessage()    {}
func (*TrxTraceRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_014579ff7d302fea, []int{2}
}

func (m *TrxTraceRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrxTraceRow.Unmarshal(m, b)
}
func (m *TrxTraceRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrxTraceRow.Marshal(b, m, deterministic)
}
func (m *TrxTraceRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrxTraceRow.Merge(m, src)
}
func (m *TrxTraceRow) XXX_Size() int {
	return xxx_messageInfo_TrxTraceRow.Size(m)
}
func (m *TrxTraceRow) XXX_DiscardUnknown() {
	xxx_messageInfo_TrxTraceRow.DiscardUnknown(m)
}

var xxx_messageInfo_TrxTraceRow proto.InternalMessageInfo

func (m *TrxTraceRow) GetTrxTrace() *v1.TransactionTrace {
	if m != nil {
		return m.TrxTrace
	}
	return nil
}

func (m *TrxTraceRow) GetBlockHeader() *v1.BlockHeader {
	if m != nil {
		return m.BlockHeader
	}
	return nil
}

type DtrxRow struct {
	SignedTrx            *v1.SignedTransaction `protobuf:"bytes,1,opt,name=signed_trx,json=signedTrx,proto3" json:"signed_trx,omitempty"`
	CreatedBy            *v1.ExtDTrxOp         `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CanceledBy           *v1.ExtDTrxOp         `protobuf:"bytes,3,opt,name=canceled_by,json=canceledBy,proto3" json:"canceled_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DtrxRow) Reset()         { *m = DtrxRow{} }
func (m *DtrxRow) String() string { return proto.CompactTextString(m) }
func (*DtrxRow) ProtoMessage()    {}
func (*DtrxRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_014579ff7d302fea, []int{3}
}

func (m *DtrxRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DtrxRow.Unmarshal(m, b)
}
func (m *DtrxRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DtrxRow.Marshal(b, m, deterministic)
}
func (m *DtrxRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DtrxRow.Merge(m, src)
}
func (m *DtrxRow) XXX_Size() int {
	return xxx_messageInfo_DtrxRow.Size(m)
}
func (m *DtrxRow) XXX_DiscardUnknown() {
	xxx_messageInfo_DtrxRow.DiscardUnknown(m)
}

var xxx_messageInfo_DtrxRow proto.InternalMessageInfo

func (m *DtrxRow) GetSignedTrx() *v1.SignedTransaction {
	if m != nil {
		return m.SignedTrx
	}
	return nil
}

func (m *DtrxRow) GetCreatedBy() *v1.ExtDTrxOp {
	if m != nil {
		return m.CreatedBy
	}
	return nil
}

func (m *DtrxRow) GetCanceledBy() *v1.ExtDTrxOp {
	if m != nil {
		return m.CanceledBy
	}
	return nil
}

type BlockRow struct {
	Block                *v1.Block           `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	ImplicitTrxRefs      *v1.TransactionRefs `protobuf:"bytes,2,opt,name=implicit_trx_refs,json=implicitTrxRefs,proto3" json:"implicit_trx_refs,omitempty"`
	TrxRefs              *v1.TransactionRefs `protobuf:"bytes,3,opt,name=trx_refs,json=trxRefs,proto3" json:"trx_refs,omitempty"`
	TraceRefs            *v1.TransactionRefs `protobuf:"bytes,4,opt,name=trace_refs,json=traceRefs,proto3" json:"trace_refs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BlockRow) Reset()         { *m = BlockRow{} }
func (m *BlockRow) String() string { return proto.CompactTextString(m) }
func (*BlockRow) ProtoMessage()    {}
func (*BlockRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_014579ff7d302fea, []int{4}
}

func (m *BlockRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRow.Unmarshal(m, b)
}
func (m *BlockRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRow.Marshal(b, m, deterministic)
}
func (m *BlockRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRow.Merge(m, src)
}
func (m *BlockRow) XXX_Size() int {
	return xxx_messageInfo_BlockRow.Size(m)
}
func (m *BlockRow) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRow.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRow proto.InternalMessageInfo

func (m *BlockRow) GetBlock() *v1.Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *BlockRow) GetImplicitTrxRefs() *v1.TransactionRefs {
	if m != nil {
		return m.ImplicitTrxRefs
	}
	return nil
}

func (m *BlockRow) GetTrxRefs() *v1.TransactionRefs {
	if m != nil {
		return m.TrxRefs
	}
	return nil
}

func (m *BlockRow) GetTraceRefs() *v1.TransactionRefs {
	if m != nil {
		return m.TraceRefs
	}
	return nil
}

type AccountRow struct {
	// Key will be account:block_id    // block_id, block_num and account implicit in key
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Creator              string               `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	BlockId              string               `protobuf:"bytes,3,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	TrxId                string               `protobuf:"bytes,4,opt,name=trx_id,json=trxId,proto3" json:"trx_id,omitempty"`
	BlockTime            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=block_time,json=blockTime,proto3" json:"block_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AccountRow) Reset()         { *m = AccountRow{} }
func (m *AccountRow) String() string { return proto.CompactTextString(m) }
func (*AccountRow) ProtoMessage()    {}
func (*AccountRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_014579ff7d302fea, []int{5}
}

func (m *AccountRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRow.Unmarshal(m, b)
}
func (m *AccountRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRow.Marshal(b, m, deterministic)
}
func (m *AccountRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRow.Merge(m, src)
}
func (m *AccountRow) XXX_Size() int {
	return xxx_messageInfo_AccountRow.Size(m)
}
func (m *AccountRow) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRow.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRow proto.InternalMessageInfo

func (m *AccountRow) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AccountRow) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *AccountRow) GetBlockId() string {
	if m != nil {
		return m.BlockId
	}
	return ""
}

func (m *AccountRow) GetTrxId() string {
	if m != nil {
		return m.TrxId
	}
	return ""
}

func (m *AccountRow) GetBlockTime() *timestamp.Timestamp {
	if m != nil {
		return m.BlockTime
	}
	return nil
}

func init() {
	proto.RegisterEnum("dfuse.eosio.trxdb.v1.IndexableRow", IndexableRow_name, IndexableRow_value)
	proto.RegisterType((*ImplicitTrxRow)(nil), "dfuse.eosio.trxdb.v1.ImplicitTrxRow")
	proto.RegisterType((*TrxRow)(nil), "dfuse.eosio.trxdb.v1.TrxRow")
	proto.RegisterType((*TrxTraceRow)(nil), "dfuse.eosio.trxdb.v1.TrxTraceRow")
	proto.RegisterType((*DtrxRow)(nil), "dfuse.eosio.trxdb.v1.DtrxRow")
	proto.RegisterType((*BlockRow)(nil), "dfuse.eosio.trxdb.v1.BlockRow")
	proto.RegisterType((*AccountRow)(nil), "dfuse.eosio.trxdb.v1.AccountRow")
}

func init() { proto.RegisterFile("dfuse/eosio/trxdb/v1/trxdb.proto", fileDescriptor_014579ff7d302fea) }

var fileDescriptor_014579ff7d302fea = []byte{
	// 680 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x5d, 0x6f, 0xd3, 0x3c,
	0x14, 0x7e, 0xb3, 0xae, 0x1f, 0x39, 0x9d, 0xde, 0xb7, 0xf3, 0xcb, 0xb6, 0xae, 0x93, 0x58, 0xa9,
	0x04, 0x4c, 0x48, 0xa4, 0xea, 0xb8, 0x42, 0x48, 0xb0, 0x7e, 0x21, 0xa2, 0x75, 0xeb, 0x30, 0x41,
	0x4c, 0xdc, 0x44, 0x89, 0xe3, 0x76, 0xd6, 0xda, 0x3a, 0x72, 0xdc, 0x91, 0xfe, 0x93, 0xfd, 0x03,
	0xfe, 0x0b, 0xb7, 0x5c, 0xf0, 0x77, 0x50, 0xec, 0x74, 0x5b, 0xa1, 0x82, 0x4d, 0xda, 0xdd, 0x39,
	0x3e, 0xcf, 0xf3, 0xd8, 0x8f, 0xed, 0x73, 0xa0, 0x1a, 0x0c, 0xa6, 0x11, 0xad, 0x53, 0x1e, 0x31,
	0x5e, 0x97, 0x22, 0x0e, 0xfc, 0xfa, 0x45, 0x43, 0x07, 0x56, 0x28, 0xb8, 0xe4, 0xe8, 0x81, 0x42,
	0x58, 0x0a, 0x61, 0xe9, 0xc2, 0x45, 0xa3, 0xb2, 0xc0, 0x23, 0x3c, 0xa0, 0x24, 0xe1, 0xa9, 0x40,
	0xf3, 0x2a, 0xbb, 0x43, 0xce, 0x87, 0x23, 0x5a, 0x57, 0x99, 0x3f, 0x1d, 0xd4, 0x25, 0x1b, 0xd3,
	0x48, 0x7a, 0xe3, 0x50, 0x03, 0x6a, 0x23, 0xf8, 0xd7, 0x1e, 0x87, 0x23, 0x46, 0x98, 0x74, 0x44,
	0x8c, 0xf9, 0x17, 0xf4, 0x16, 0x20, 0x62, 0xc3, 0x09, 0x0d, 0x5c, 0x29, 0xe2, 0xb2, 0x51, 0x35,
	0xf6, 0x8a, 0xfb, 0x4f, 0xad, 0x9b, 0xfb, 0xeb, 0x0d, 0x2e, 0x1a, 0xd6, 0x07, 0x85, 0x73, 0x84,
	0x37, 0x89, 0x3c, 0x22, 0x19, 0x9f, 0x60, 0x33, 0x4a, 0x97, 0x62, 0x84, 0x60, 0x75, 0xe2, 0x8d,
	0x69, 0x79, 0xa5, 0x6a, 0xec, 0x99, 0x58, 0xc5, 0xb5, 0x1f, 0x06, 0xe4, 0xee, 0x79, 0x9b, 0x16,
	0xe4, 0x05, 0x25, 0x94, 0x85, 0x52, 0xed, 0x54, 0xdc, 0xdf, 0x5b, 0x2e, 0x72, 0x93, 0xae, 0xf1,
	0x78, 0x4e, 0x44, 0x4d, 0x28, 0x86, 0x53, 0x7f, 0xc4, 0x88, 0x7b, 0x4e, 0x67, 0x51, 0x39, 0xa3,
	0x74, 0xaa, 0xcb, 0x75, 0x4e, 0x14, 0xf0, 0x90, 0xce, 0x22, 0x0c, 0xe1, 0x55, 0x5c, 0xbb, 0x34,
	0xa0, 0xe8, 0x88, 0xd8, 0x11, 0x1e, 0xa1, 0x89, 0xbd, 0x36, 0x98, 0x52, 0xc4, 0xae, 0x4c, 0xf2,
	0xd4, 0xdd, 0x93, 0xbf, 0x1e, 0x4c, 0xb3, 0x0b, 0x32, 0xd5, 0x41, 0x1d, 0x58, 0xf3, 0x47, 0x9c,
	0x9c, 0xbb, 0x67, 0xd4, 0x0b, 0xa8, 0x48, 0x0d, 0x3e, 0x5a, 0xae, 0xd3, 0x4a, 0x90, 0xef, 0x14,
	0x10, 0x17, 0xfd, 0xeb, 0xa4, 0xf6, 0xdd, 0x80, 0x7c, 0x47, 0xde, 0xef, 0xad, 0xbf, 0x06, 0x20,
	0x82, 0x7a, 0x92, 0x06, 0xae, 0x3f, 0x4b, 0xcf, 0xb5, 0xbb, 0x5c, 0xa7, 0x1b, 0xcb, 0x8e, 0x23,
	0xe2, 0x7e, 0x88, 0xcd, 0x94, 0xd2, 0x9a, 0xa1, 0x03, 0x28, 0x12, 0x6f, 0x42, 0xe8, 0x48, 0x0b,
	0x64, 0x6e, 0x27, 0x00, 0x73, 0x4e, 0x6b, 0x56, 0xbb, 0x5c, 0x81, 0x82, 0xb2, 0x9c, 0xd8, 0x6a,
	0x40, 0x56, 0x39, 0x4e, 0x1d, 0xed, 0xfc, 0xe1, 0x86, 0xb0, 0x46, 0xa2, 0xf7, 0xb0, 0xce, 0xd2,
	0x8f, 0x9f, 0xdc, 0x85, 0x2b, 0xe8, 0x20, 0x4a, 0x8d, 0x3c, 0xbe, 0xc5, 0x0f, 0x1a, 0x44, 0xf8,
	0x3f, 0x76, 0xa3, 0x71, 0xe8, 0x20, 0x42, 0x07, 0x50, 0xb8, 0x52, 0xca, 0xdc, 0x45, 0x29, 0x2f,
	0x53, 0x85, 0x0e, 0x80, 0xfa, 0x31, 0x5a, 0x63, 0xf5, 0x2e, 0x1a, 0xa6, 0x22, 0x26, 0x61, 0xed,
	0xab, 0x01, 0xd0, 0x24, 0x84, 0x4f, 0x27, 0x32, 0xb9, 0x9c, 0x79, 0x23, 0x1a, 0xd7, 0x8d, 0x88,
	0xca, 0x90, 0x57, 0x8f, 0xc1, 0x45, 0xda, 0x9f, 0xf3, 0x14, 0x6d, 0x43, 0x41, 0xff, 0x39, 0x16,
	0x28, 0x13, 0x26, 0xce, 0xab, 0xdc, 0x0e, 0xd0, 0x06, 0xe4, 0x12, 0x7f, 0x2c, 0x50, 0x27, 0x33,
	0x71, 0x56, 0x8a, 0xd8, 0x0e, 0xd0, 0x4b, 0x00, 0xcd, 0x48, 0x66, 0x4b, 0x39, 0xab, 0x0e, 0x5d,
	0xb1, 0xf4, 0xe0, 0xb1, 0xe6, 0x83, 0xc7, 0x72, 0xe6, 0x83, 0x07, 0x9b, 0x0a, 0x9d, 0xe4, 0xcf,
	0xbe, 0x19, 0xb0, 0x66, 0x4f, 0x02, 0x1a, 0x7b, 0xfe, 0x48, 0xb5, 0xcd, 0x36, 0x6c, 0xd8, 0xc7,
	0x9d, 0xee, 0x69, 0xb3, 0xd5, 0xeb, 0xba, 0xb8, 0xff, 0xc9, 0x6d, 0xb6, 0xdb, 0xfd, 0x8f, 0xc7,
	0x4e, 0xe9, 0x1f, 0xb4, 0x05, 0xff, 0x2f, 0x96, 0x5a, 0xbd, 0x7e, 0xfb, 0xb0, 0x64, 0xa0, 0x4d,
	0x40, 0x8b, 0x85, 0x8e, 0x83, 0x4f, 0x4b, 0x2b, 0xe8, 0x21, 0x54, 0x16, 0xd7, 0xed, 0xa3, 0x93,
	0x9e, 0xdd, 0xb6, 0x1d, 0x37, 0xa9, 0x67, 0xd0, 0x06, 0xac, 0x2f, 0xd6, 0x93, 0xe5, 0x55, 0xb4,
	0x03, 0x5b, 0xbf, 0x2d, 0xbb, 0x0e, 0x6e, 0xb6, 0xbb, 0xa5, 0x2c, 0xaa, 0xc0, 0xe6, 0x2f, 0x45,
	0xfb, 0xa8, 0xdb, 0xb3, 0x8f, 0xbb, 0xa5, 0x5c, 0xab, 0xf9, 0xf9, 0xcd, 0x90, 0xc9, 0xb3, 0xa9,
	0x6f, 0x11, 0x3e, 0xae, 0xab, 0x47, 0x7b, 0xce, 0x78, 0x1a, 0xe8, 0x19, 0x1d, 0xfa, 0xf5, 0x65,
	0xa3, 0xfe, 0x55, 0xe8, 0xab, 0xd0, 0xcf, 0xa9, 0xeb, 0x7a, 0xf1, 0x33, 0x00, 0x00, 0xff, 0xff,
	0x07, 0xae, 0xba, 0xa3, 0x11, 0x06, 0x00, 0x00,
}
