// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dashboard.proto

package dashboard

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AppStatus int32

const (
	AppStatus_NOTFOUND AppStatus = 0
	AppStatus_CREATED  AppStatus = 1
	AppStatus_RUNNING  AppStatus = 2
	AppStatus_WARNING  AppStatus = 3
	AppStatus_STOPPED  AppStatus = 4
)

var AppStatus_name = map[int32]string{
	0: "NOTFOUND",
	1: "CREATED",
	2: "RUNNING",
	3: "WARNING",
	4: "STOPPED",
}

var AppStatus_value = map[string]int32{
	"NOTFOUND": 0,
	"CREATED":  1,
	"RUNNING":  2,
	"WARNING":  3,
	"STOPPED":  4,
}

func (x AppStatus) String() string {
	return proto.EnumName(AppStatus_name, int32(x))
}

func (AppStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{0}
}

type MetricType int32

const (
	MetricType_HEAD_BLOCK_TIME_DRIFT MetricType = 0
	MetricType_HEAD_BLOCK_NUMBER     MetricType = 1
)

var MetricType_name = map[int32]string{
	0: "HEAD_BLOCK_TIME_DRIFT",
	1: "HEAD_BLOCK_NUMBER",
}

var MetricType_value = map[string]int32{
	"HEAD_BLOCK_TIME_DRIFT": 0,
	"HEAD_BLOCK_NUMBER":     1,
}

func (x MetricType) String() string {
	return proto.EnumName(MetricType_name, int32(x))
}

func (MetricType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{1}
}

type AppsListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppsListRequest) Reset()         { *m = AppsListRequest{} }
func (m *AppsListRequest) String() string { return proto.CompactTextString(m) }
func (*AppsListRequest) ProtoMessage()    {}
func (*AppsListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{0}
}

func (m *AppsListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppsListRequest.Unmarshal(m, b)
}
func (m *AppsListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppsListRequest.Marshal(b, m, deterministic)
}
func (m *AppsListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppsListRequest.Merge(m, src)
}
func (m *AppsListRequest) XXX_Size() int {
	return xxx_messageInfo_AppsListRequest.Size(m)
}
func (m *AppsListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppsListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppsListRequest proto.InternalMessageInfo

type AppsListResponse struct {
	Apps                 []*AppInfo `protobuf:"bytes,1,rep,name=Apps,proto3" json:"Apps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AppsListResponse) Reset()         { *m = AppsListResponse{} }
func (m *AppsListResponse) String() string { return proto.CompactTextString(m) }
func (*AppsListResponse) ProtoMessage()    {}
func (*AppsListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{1}
}

func (m *AppsListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppsListResponse.Unmarshal(m, b)
}
func (m *AppsListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppsListResponse.Marshal(b, m, deterministic)
}
func (m *AppsListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppsListResponse.Merge(m, src)
}
func (m *AppsListResponse) XXX_Size() int {
	return xxx_messageInfo_AppsListResponse.Size(m)
}
func (m *AppsListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppsListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppsListResponse proto.InternalMessageInfo

func (m *AppsListResponse) GetApps() []*AppInfo {
	if m != nil {
		return m.Apps
	}
	return nil
}

type AppsInfoRequest struct {
	FilterAppId          string   `protobuf:"bytes,1,opt,name=filter_app_id,json=filterAppId,proto3" json:"filter_app_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppsInfoRequest) Reset()         { *m = AppsInfoRequest{} }
func (m *AppsInfoRequest) String() string { return proto.CompactTextString(m) }
func (*AppsInfoRequest) ProtoMessage()    {}
func (*AppsInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{2}
}

func (m *AppsInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppsInfoRequest.Unmarshal(m, b)
}
func (m *AppsInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppsInfoRequest.Marshal(b, m, deterministic)
}
func (m *AppsInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppsInfoRequest.Merge(m, src)
}
func (m *AppsInfoRequest) XXX_Size() int {
	return xxx_messageInfo_AppsInfoRequest.Size(m)
}
func (m *AppsInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppsInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppsInfoRequest proto.InternalMessageInfo

func (m *AppsInfoRequest) GetFilterAppId() string {
	if m != nil {
		return m.FilterAppId
	}
	return ""
}

type AppsInfoResponse struct {
	Apps                 []*AppInfo `protobuf:"bytes,1,rep,name=Apps,proto3" json:"Apps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AppsInfoResponse) Reset()         { *m = AppsInfoResponse{} }
func (m *AppsInfoResponse) String() string { return proto.CompactTextString(m) }
func (*AppsInfoResponse) ProtoMessage()    {}
func (*AppsInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{3}
}

func (m *AppsInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppsInfoResponse.Unmarshal(m, b)
}
func (m *AppsInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppsInfoResponse.Marshal(b, m, deterministic)
}
func (m *AppsInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppsInfoResponse.Merge(m, src)
}
func (m *AppsInfoResponse) XXX_Size() int {
	return xxx_messageInfo_AppsInfoResponse.Size(m)
}
func (m *AppsInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppsInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppsInfoResponse proto.InternalMessageInfo

func (m *AppsInfoResponse) GetApps() []*AppInfo {
	if m != nil {
		return m.Apps
	}
	return nil
}

type AppInfo struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string    `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status               AppStatus `protobuf:"varint,4,opt,name=status,proto3,enum=dashboard.AppStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AppInfo) Reset()         { *m = AppInfo{} }
func (m *AppInfo) String() string { return proto.CompactTextString(m) }
func (*AppInfo) ProtoMessage()    {}
func (*AppInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{4}
}

func (m *AppInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppInfo.Unmarshal(m, b)
}
func (m *AppInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppInfo.Marshal(b, m, deterministic)
}
func (m *AppInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppInfo.Merge(m, src)
}
func (m *AppInfo) XXX_Size() int {
	return xxx_messageInfo_AppInfo.Size(m)
}
func (m *AppInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AppInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AppInfo proto.InternalMessageInfo

func (m *AppInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AppInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AppInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AppInfo) GetStatus() AppStatus {
	if m != nil {
		return m.Status
	}
	return AppStatus_NOTFOUND
}

type AppsMetricsRequest struct {
	FilterAppId          string   `protobuf:"bytes,1,opt,name=filter_app_id,json=filterAppId,proto3" json:"filter_app_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppsMetricsRequest) Reset()         { *m = AppsMetricsRequest{} }
func (m *AppsMetricsRequest) String() string { return proto.CompactTextString(m) }
func (*AppsMetricsRequest) ProtoMessage()    {}
func (*AppsMetricsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{5}
}

func (m *AppsMetricsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppsMetricsRequest.Unmarshal(m, b)
}
func (m *AppsMetricsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppsMetricsRequest.Marshal(b, m, deterministic)
}
func (m *AppsMetricsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppsMetricsRequest.Merge(m, src)
}
func (m *AppsMetricsRequest) XXX_Size() int {
	return xxx_messageInfo_AppsMetricsRequest.Size(m)
}
func (m *AppsMetricsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppsMetricsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppsMetricsRequest proto.InternalMessageInfo

func (m *AppsMetricsRequest) GetFilterAppId() string {
	if m != nil {
		return m.FilterAppId
	}
	return ""
}

type AppMetricsResponse struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metrics              []*Metric `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Title                string    `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AppMetricsResponse) Reset()         { *m = AppMetricsResponse{} }
func (m *AppMetricsResponse) String() string { return proto.CompactTextString(m) }
func (*AppMetricsResponse) ProtoMessage()    {}
func (*AppMetricsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{6}
}

func (m *AppMetricsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppMetricsResponse.Unmarshal(m, b)
}
func (m *AppMetricsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppMetricsResponse.Marshal(b, m, deterministic)
}
func (m *AppMetricsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppMetricsResponse.Merge(m, src)
}
func (m *AppMetricsResponse) XXX_Size() int {
	return xxx_messageInfo_AppMetricsResponse.Size(m)
}
func (m *AppMetricsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppMetricsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppMetricsResponse proto.InternalMessageInfo

func (m *AppMetricsResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AppMetricsResponse) GetMetrics() []*Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *AppMetricsResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type Metric struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value                float32              `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	Type                 MetricType           `protobuf:"varint,3,opt,name=type,proto3,enum=dashboard.MetricType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{7}
}

func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (m *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(m, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

func (m *Metric) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Metric) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Metric) GetType() MetricType {
	if m != nil {
		return m.Type
	}
	return MetricType_HEAD_BLOCK_TIME_DRIFT
}

type StartAppRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartAppRequest) Reset()         { *m = StartAppRequest{} }
func (m *StartAppRequest) String() string { return proto.CompactTextString(m) }
func (*StartAppRequest) ProtoMessage()    {}
func (*StartAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{8}
}

func (m *StartAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartAppRequest.Unmarshal(m, b)
}
func (m *StartAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartAppRequest.Marshal(b, m, deterministic)
}
func (m *StartAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartAppRequest.Merge(m, src)
}
func (m *StartAppRequest) XXX_Size() int {
	return xxx_messageInfo_StartAppRequest.Size(m)
}
func (m *StartAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartAppRequest proto.InternalMessageInfo

func (m *StartAppRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

type StartAppResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartAppResponse) Reset()         { *m = StartAppResponse{} }
func (m *StartAppResponse) String() string { return proto.CompactTextString(m) }
func (*StartAppResponse) ProtoMessage()    {}
func (*StartAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{9}
}

func (m *StartAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartAppResponse.Unmarshal(m, b)
}
func (m *StartAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartAppResponse.Marshal(b, m, deterministic)
}
func (m *StartAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartAppResponse.Merge(m, src)
}
func (m *StartAppResponse) XXX_Size() int {
	return xxx_messageInfo_StartAppResponse.Size(m)
}
func (m *StartAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartAppResponse proto.InternalMessageInfo

type StopAppRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopAppRequest) Reset()         { *m = StopAppRequest{} }
func (m *StopAppRequest) String() string { return proto.CompactTextString(m) }
func (*StopAppRequest) ProtoMessage()    {}
func (*StopAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{10}
}

func (m *StopAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopAppRequest.Unmarshal(m, b)
}
func (m *StopAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopAppRequest.Marshal(b, m, deterministic)
}
func (m *StopAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopAppRequest.Merge(m, src)
}
func (m *StopAppRequest) XXX_Size() int {
	return xxx_messageInfo_StopAppRequest.Size(m)
}
func (m *StopAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopAppRequest proto.InternalMessageInfo

func (m *StopAppRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

type StopAppResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopAppResponse) Reset()         { *m = StopAppResponse{} }
func (m *StopAppResponse) String() string { return proto.CompactTextString(m) }
func (*StopAppResponse) ProtoMessage()    {}
func (*StopAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{11}
}

func (m *StopAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopAppResponse.Unmarshal(m, b)
}
func (m *StopAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopAppResponse.Marshal(b, m, deterministic)
}
func (m *StopAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopAppResponse.Merge(m, src)
}
func (m *StopAppResponse) XXX_Size() int {
	return xxx_messageInfo_StopAppResponse.Size(m)
}
func (m *StopAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopAppResponse proto.InternalMessageInfo

type DmeshRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DmeshRequest) Reset()         { *m = DmeshRequest{} }
func (m *DmeshRequest) String() string { return proto.CompactTextString(m) }
func (*DmeshRequest) ProtoMessage()    {}
func (*DmeshRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{12}
}

func (m *DmeshRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DmeshRequest.Unmarshal(m, b)
}
func (m *DmeshRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DmeshRequest.Marshal(b, m, deterministic)
}
func (m *DmeshRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DmeshRequest.Merge(m, src)
}
func (m *DmeshRequest) XXX_Size() int {
	return xxx_messageInfo_DmeshRequest.Size(m)
}
func (m *DmeshRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DmeshRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DmeshRequest proto.InternalMessageInfo

type DmeshResponse struct {
	Clients              []*DmeshClient `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DmeshResponse) Reset()         { *m = DmeshResponse{} }
func (m *DmeshResponse) String() string { return proto.CompactTextString(m) }
func (*DmeshResponse) ProtoMessage()    {}
func (*DmeshResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{13}
}

func (m *DmeshResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DmeshResponse.Unmarshal(m, b)
}
func (m *DmeshResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DmeshResponse.Marshal(b, m, deterministic)
}
func (m *DmeshResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DmeshResponse.Merge(m, src)
}
func (m *DmeshResponse) XXX_Size() int {
	return xxx_messageInfo_DmeshResponse.Size(m)
}
func (m *DmeshResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DmeshResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DmeshResponse proto.InternalMessageInfo

func (m *DmeshResponse) GetClients() []*DmeshClient {
	if m != nil {
		return m.Clients
	}
	return nil
}

type DmeshClient struct {
	Host                 string               `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Ready                bool                 `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	Boot                 *timestamp.Timestamp `protobuf:"bytes,3,opt,name=boot,proto3" json:"boot,omitempty"`
	ServesResolveForks   bool                 `protobuf:"varint,4,opt,name=serves_resolveForks,json=servesResolveForks,proto3" json:"serves_resolveForks,omitempty"`
	ServesReversible     bool                 `protobuf:"varint,5,opt,name=serves_reversible,json=servesReversible,proto3" json:"serves_reversible,omitempty"`
	HasMovingHead        bool                 `protobuf:"varint,6,opt,name=has_moving_head,json=hasMovingHead,proto3" json:"has_moving_head,omitempty"`
	HasMovingTail        bool                 `protobuf:"varint,7,opt,name=has_moving_tail,json=hasMovingTail,proto3" json:"has_moving_tail,omitempty"`
	ShardSize            uint64               `protobuf:"varint,8,opt,name=shard_size,json=shardSize,proto3" json:"shard_size,omitempty"`
	TierLevel            uint32               `protobuf:"varint,9,opt,name=tier_level,json=tierLevel,proto3" json:"tier_level,omitempty"`
	TailBlockNum         uint64               `protobuf:"varint,10,opt,name=tail_block_num,json=tailBlockNum,proto3" json:"tail_block_num,omitempty"`
	TailBlockId          string               `protobuf:"bytes,11,opt,name=tail_block_id,json=tailBlockId,proto3" json:"tail_block_id,omitempty"`
	IrrBlockNum          uint64               `protobuf:"varint,12,opt,name=irr_block_num,json=irrBlockNum,proto3" json:"irr_block_num,omitempty"`
	IrrBlockId           string               `protobuf:"bytes,13,opt,name=irr_block_id,json=irrBlockId,proto3" json:"irr_block_id,omitempty"`
	HeadBlockNum         uint64               `protobuf:"varint,14,opt,name=head_block_num,json=headBlockNum,proto3" json:"head_block_num,omitempty"`
	HeadBlockId          string               `protobuf:"bytes,15,opt,name=head_block_id,json=headBlockId,proto3" json:"head_block_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DmeshClient) Reset()         { *m = DmeshClient{} }
func (m *DmeshClient) String() string { return proto.CompactTextString(m) }
func (*DmeshClient) ProtoMessage()    {}
func (*DmeshClient) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{14}
}

func (m *DmeshClient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DmeshClient.Unmarshal(m, b)
}
func (m *DmeshClient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DmeshClient.Marshal(b, m, deterministic)
}
func (m *DmeshClient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DmeshClient.Merge(m, src)
}
func (m *DmeshClient) XXX_Size() int {
	return xxx_messageInfo_DmeshClient.Size(m)
}
func (m *DmeshClient) XXX_DiscardUnknown() {
	xxx_messageInfo_DmeshClient.DiscardUnknown(m)
}

var xxx_messageInfo_DmeshClient proto.InternalMessageInfo

func (m *DmeshClient) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *DmeshClient) GetReady() bool {
	if m != nil {
		return m.Ready
	}
	return false
}

func (m *DmeshClient) GetBoot() *timestamp.Timestamp {
	if m != nil {
		return m.Boot
	}
	return nil
}

func (m *DmeshClient) GetServesResolveForks() bool {
	if m != nil {
		return m.ServesResolveForks
	}
	return false
}

func (m *DmeshClient) GetServesReversible() bool {
	if m != nil {
		return m.ServesReversible
	}
	return false
}

func (m *DmeshClient) GetHasMovingHead() bool {
	if m != nil {
		return m.HasMovingHead
	}
	return false
}

func (m *DmeshClient) GetHasMovingTail() bool {
	if m != nil {
		return m.HasMovingTail
	}
	return false
}

func (m *DmeshClient) GetShardSize() uint64 {
	if m != nil {
		return m.ShardSize
	}
	return 0
}

func (m *DmeshClient) GetTierLevel() uint32 {
	if m != nil {
		return m.TierLevel
	}
	return 0
}

func (m *DmeshClient) GetTailBlockNum() uint64 {
	if m != nil {
		return m.TailBlockNum
	}
	return 0
}

func (m *DmeshClient) GetTailBlockId() string {
	if m != nil {
		return m.TailBlockId
	}
	return ""
}

func (m *DmeshClient) GetIrrBlockNum() uint64 {
	if m != nil {
		return m.IrrBlockNum
	}
	return 0
}

func (m *DmeshClient) GetIrrBlockId() string {
	if m != nil {
		return m.IrrBlockId
	}
	return ""
}

func (m *DmeshClient) GetHeadBlockNum() uint64 {
	if m != nil {
		return m.HeadBlockNum
	}
	return 0
}

func (m *DmeshClient) GetHeadBlockId() string {
	if m != nil {
		return m.HeadBlockId
	}
	return ""
}

func init() {
	proto.RegisterEnum("dashboard.AppStatus", AppStatus_name, AppStatus_value)
	proto.RegisterEnum("dashboard.MetricType", MetricType_name, MetricType_value)
	proto.RegisterType((*AppsListRequest)(nil), "dashboard.AppsListRequest")
	proto.RegisterType((*AppsListResponse)(nil), "dashboard.AppsListResponse")
	proto.RegisterType((*AppsInfoRequest)(nil), "dashboard.AppsInfoRequest")
	proto.RegisterType((*AppsInfoResponse)(nil), "dashboard.AppsInfoResponse")
	proto.RegisterType((*AppInfo)(nil), "dashboard.AppInfo")
	proto.RegisterType((*AppsMetricsRequest)(nil), "dashboard.AppsMetricsRequest")
	proto.RegisterType((*AppMetricsResponse)(nil), "dashboard.AppMetricsResponse")
	proto.RegisterType((*Metric)(nil), "dashboard.Metric")
	proto.RegisterType((*StartAppRequest)(nil), "dashboard.StartAppRequest")
	proto.RegisterType((*StartAppResponse)(nil), "dashboard.StartAppResponse")
	proto.RegisterType((*StopAppRequest)(nil), "dashboard.StopAppRequest")
	proto.RegisterType((*StopAppResponse)(nil), "dashboard.StopAppResponse")
	proto.RegisterType((*DmeshRequest)(nil), "dashboard.DmeshRequest")
	proto.RegisterType((*DmeshResponse)(nil), "dashboard.DmeshResponse")
	proto.RegisterType((*DmeshClient)(nil), "dashboard.DmeshClient")
}

func init() { proto.RegisterFile("dashboard.proto", fileDescriptor_9b97678da3a35dfb) }

var fileDescriptor_9b97678da3a35dfb = []byte{
	// 899 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x5b, 0x8f, 0xda, 0x46,
	0x14, 0x8e, 0x81, 0xe5, 0x72, 0xcc, 0xc5, 0x4c, 0xb3, 0xad, 0x43, 0x15, 0x15, 0x59, 0x55, 0x4a,
	0x93, 0x8a, 0x5d, 0x51, 0x55, 0x8a, 0xf2, 0x50, 0x95, 0x05, 0xb6, 0x41, 0x5d, 0xd8, 0x68, 0x60,
	0x55, 0xa9, 0x2f, 0x96, 0x59, 0xcf, 0x2e, 0xa3, 0x18, 0xec, 0xce, 0x0c, 0x48, 0x9b, 0x97, 0x3e,
	0xf4, 0xd7, 0xf4, 0xa1, 0xff, 0xb1, 0x9a, 0x19, 0xdb, 0x18, 0x6f, 0xd4, 0x28, 0x6f, 0x3e, 0xdf,
	0xf9, 0xce, 0x77, 0x2e, 0x3a, 0x73, 0x0c, 0x2d, 0xdf, 0xe3, 0xeb, 0x55, 0xe8, 0x31, 0xbf, 0x1f,
	0xb1, 0x50, 0x84, 0xa8, 0x96, 0x02, 0x9d, 0x6f, 0xee, 0xc3, 0xf0, 0x3e, 0x20, 0x67, 0xca, 0xb1,
	0xda, 0xdd, 0x9d, 0x09, 0xba, 0x21, 0x5c, 0x78, 0x9b, 0x48, 0x73, 0x9d, 0x36, 0xb4, 0x86, 0x51,
	0xc4, 0xaf, 0x28, 0x17, 0x98, 0xfc, 0xb9, 0x23, 0x5c, 0x38, 0x6f, 0xc0, 0x3a, 0x40, 0x3c, 0x0a,
	0xb7, 0x9c, 0xa0, 0x17, 0x50, 0x92, 0x98, 0x6d, 0x74, 0x8b, 0x3d, 0x73, 0x80, 0xfa, 0x87, 0x94,
	0xc3, 0x28, 0x9a, 0x6e, 0xef, 0x42, 0xac, 0xfc, 0xce, 0x4f, 0x5a, 0x4e, 0x21, 0x5a, 0x0e, 0x39,
	0xd0, 0xb8, 0xa3, 0x81, 0x20, 0xcc, 0xf5, 0xa2, 0xc8, 0xa5, 0xbe, 0x6d, 0x74, 0x8d, 0x5e, 0x0d,
	0x9b, 0x1a, 0x94, 0xe1, 0x7e, 0x92, 0x52, 0x87, 0x7d, 0x66, 0xca, 0xbf, 0xa0, 0x12, 0x03, 0xa8,
	0x09, 0x85, 0x54, 0xbf, 0x40, 0x7d, 0xf4, 0x14, 0x4e, 0x04, 0x15, 0x01, 0xb1, 0x0b, 0x0a, 0xd2,
	0x06, 0xea, 0x82, 0xe9, 0x13, 0x7e, 0xcb, 0x68, 0x24, 0x68, 0xb8, 0xb5, 0x8b, 0xba, 0x9c, 0x0c,
	0x84, 0x7e, 0x80, 0x32, 0x17, 0x9e, 0xd8, 0x71, 0xbb, 0xd4, 0x35, 0x7a, 0xcd, 0xc1, 0xd3, 0xe3,
	0xe4, 0x0b, 0xe5, 0xc3, 0x31, 0xc7, 0x79, 0x0d, 0x48, 0x16, 0x32, 0x23, 0x82, 0xd1, 0x5b, 0xfe,
	0x39, 0x6d, 0xdf, 0xab, 0xc8, 0x34, 0x30, 0x6e, 0x3c, 0xdf, 0xc5, 0x2b, 0xa8, 0x6c, 0x34, 0xc5,
	0x2e, 0xa8, 0x59, 0xb4, 0x33, 0xe5, 0xe8, 0x60, 0x9c, 0x30, 0x0e, 0x2d, 0x17, 0x33, 0x2d, 0x3b,
	0x7f, 0x1b, 0x50, 0xd6, 0x4c, 0xf4, 0x1a, 0x6a, 0xe9, 0x0e, 0xa8, 0x24, 0xe6, 0xa0, 0xd3, 0xd7,
	0x5b, 0xd2, 0x4f, 0xb6, 0xa4, 0xbf, 0x4c, 0x18, 0xf8, 0x40, 0x96, 0xd2, 0x7b, 0x2f, 0xd8, 0xe9,
	0x69, 0x16, 0xb0, 0x36, 0xd0, 0xf7, 0x50, 0x12, 0x0f, 0x91, 0xce, 0xd7, 0x1c, 0x9c, 0x3e, 0x2a,
	0x6d, 0xf9, 0x10, 0x11, 0xac, 0x28, 0x4e, 0x0f, 0x5a, 0x0b, 0xe1, 0x31, 0x31, 0x8c, 0xa2, 0x64,
	0x4a, 0xa7, 0x50, 0x3e, 0x1a, 0xcf, 0x89, 0xa7, 0x06, 0x83, 0xc0, 0x3a, 0x30, 0xf5, 0x58, 0x9c,
	0xef, 0xa0, 0xb9, 0x10, 0x61, 0xf4, 0xe9, 0xe0, 0xb6, 0x4c, 0x13, 0x13, 0xe3, 0xd8, 0x26, 0xd4,
	0xc7, 0x1b, 0xc2, 0xd7, 0xc9, 0x8a, 0x0f, 0xa1, 0x11, 0xdb, 0xf1, 0xcc, 0xcf, 0xa1, 0x72, 0x1b,
	0x50, 0xb2, 0x15, 0xc9, 0xbe, 0x7d, 0x99, 0x69, 0x44, 0x51, 0x47, 0xca, 0x8d, 0x13, 0x9a, 0xf3,
	0x6f, 0x09, 0xcc, 0x8c, 0x03, 0x21, 0x28, 0xad, 0x43, 0x2e, 0xe2, 0x52, 0xd4, 0xb7, 0x9c, 0x18,
	0x23, 0x9e, 0xff, 0xa0, 0x26, 0x56, 0xc5, 0xda, 0x40, 0x7d, 0x28, 0xad, 0xc2, 0x50, 0xa8, 0x89,
	0xfd, 0xff, 0xf0, 0x15, 0x0f, 0x9d, 0xc1, 0x17, 0x9c, 0xb0, 0x3d, 0xe1, 0x2e, 0x23, 0x3c, 0x0c,
	0xf6, 0xe4, 0x32, 0x64, 0xef, 0xf5, 0x6a, 0x56, 0x31, 0xd2, 0x2e, 0x9c, 0xf1, 0xa0, 0x57, 0xd0,
	0x4e, 0x03, 0xf6, 0x84, 0x71, 0xba, 0x0a, 0x88, 0x7d, 0xa2, 0xe8, 0x56, 0x42, 0x4f, 0x70, 0xf4,
	0x02, 0x5a, 0x6b, 0x8f, 0xbb, 0x9b, 0x70, 0x4f, 0xb7, 0xf7, 0xee, 0x9a, 0x78, 0xbe, 0x5d, 0x56,
	0xd4, 0xc6, 0xda, 0xe3, 0x33, 0x85, 0xbe, 0x25, 0x9e, 0x9f, 0xe3, 0x09, 0x8f, 0x06, 0x76, 0x25,
	0xc7, 0x5b, 0x7a, 0x34, 0x40, 0xcf, 0x01, 0xf8, 0xda, 0x63, 0xbe, 0xcb, 0xe9, 0x07, 0x62, 0x57,
	0xbb, 0x46, 0xaf, 0x84, 0x6b, 0x0a, 0x59, 0xd0, 0x0f, 0x44, 0xba, 0x05, 0x25, 0xcc, 0x0d, 0xc8,
	0x9e, 0x04, 0x76, 0xad, 0x6b, 0xf4, 0x1a, 0x72, 0xc7, 0x08, 0xbb, 0x92, 0x00, 0xfa, 0x16, 0x9a,
	0x52, 0xda, 0x5d, 0x05, 0xe1, 0xed, 0x7b, 0x77, 0xbb, 0xdb, 0xd8, 0xa0, 0x14, 0xea, 0x12, 0xbd,
	0x90, 0xe0, 0x7c, 0xb7, 0x91, 0x6f, 0x2b, 0xc3, 0xa2, 0xbe, 0x6d, 0xea, 0xb7, 0x95, 0x92, 0xa6,
	0xbe, 0xe4, 0x50, 0xc6, 0x32, 0x42, 0x75, 0x25, 0x64, 0x52, 0xc6, 0x52, 0x9d, 0x2e, 0xd4, 0x0f,
	0x1c, 0xea, 0xdb, 0x0d, 0x25, 0x03, 0x09, 0x65, 0xea, 0xcb, 0x7a, 0xe4, 0x48, 0x32, 0x32, 0x4d,
	0x5d, 0x8f, 0x44, 0xb3, 0xf5, 0x64, 0x58, 0xd4, 0xb7, 0x5b, 0xba, 0x9e, 0x94, 0x34, 0xf5, 0x5f,
	0xce, 0xa0, 0x96, 0x9e, 0x0e, 0x54, 0x87, 0xea, 0xfc, 0x7a, 0x79, 0x79, 0x7d, 0x33, 0x1f, 0x5b,
	0x4f, 0x90, 0x09, 0x95, 0x11, 0x9e, 0x0c, 0x97, 0x93, 0xb1, 0x65, 0x48, 0x03, 0xdf, 0xcc, 0xe7,
	0xd3, 0xf9, 0xaf, 0x56, 0x41, 0x1a, 0xbf, 0x0f, 0xb1, 0x32, 0x8a, 0xd2, 0x58, 0x2c, 0xaf, 0xdf,
	0xbd, 0x9b, 0x8c, 0xad, 0xd2, 0xcb, 0x9f, 0x01, 0x0e, 0xef, 0x0b, 0x3d, 0x83, 0xd3, 0xb7, 0x93,
	0xe1, 0xd8, 0xbd, 0xb8, 0xba, 0x1e, 0xfd, 0xe6, 0x2e, 0xa7, 0xb3, 0x89, 0x3b, 0xc6, 0xd3, 0xcb,
	0xa5, 0xf5, 0x04, 0x9d, 0x42, 0x3b, 0xe3, 0x9a, 0xdf, 0xcc, 0x2e, 0x26, 0xd8, 0x32, 0x06, 0xff,
	0x14, 0xa1, 0x36, 0x4e, 0x36, 0x1c, 0x8d, 0xa0, 0x9a, 0x9c, 0x7c, 0xd4, 0x39, 0x3e, 0x76, 0xd9,
	0x5f, 0x43, 0xe7, 0xeb, 0x8f, 0xfa, 0xe2, 0x37, 0x34, 0xd1, 0x22, 0xea, 0x12, 0xe7, 0x45, 0x32,
	0x3f, 0x84, 0x47, 0x22, 0xd9, 0xab, 0x7f, 0x6e, 0xa0, 0x19, 0x98, 0x99, 0x73, 0x8a, 0x9e, 0xe7,
	0xd8, 0xc7, 0x67, 0xb6, 0x93, 0x73, 0xe7, 0x6e, 0xe9, 0xb9, 0x81, 0xde, 0xc0, 0x89, 0x7a, 0xa6,
	0xe8, 0xab, 0xfc, 0x8b, 0x4e, 0x24, 0xec, 0xc7, 0x8e, 0xb8, 0xa3, 0x11, 0x54, 0x93, 0x33, 0x74,
	0xd4, 0x51, 0xee, 0x8a, 0x1d, 0x75, 0x94, 0xbf, 0x5b, 0xe8, 0x17, 0xa8, 0xc4, 0xe7, 0x08, 0x3d,
	0x3b, 0xe2, 0x65, 0x6f, 0x59, 0xa7, 0xf3, 0x31, 0x97, 0x56, 0xb8, 0x30, 0xff, 0x38, 0xfc, 0xd1,
	0x57, 0x65, 0x75, 0x27, 0x7e, 0xfc, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x94, 0x02, 0x01, 0x49, 0xf6,
	0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DashboardClient is the client API for Dashboard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DashboardClient interface {
	AppsList(ctx context.Context, in *AppsListRequest, opts ...grpc.CallOption) (*AppsListResponse, error)
	AppsInfo(ctx context.Context, in *AppsInfoRequest, opts ...grpc.CallOption) (Dashboard_AppsInfoClient, error)
	AppsMetrics(ctx context.Context, in *AppsMetricsRequest, opts ...grpc.CallOption) (Dashboard_AppsMetricsClient, error)
	Dmesh(ctx context.Context, in *DmeshRequest, opts ...grpc.CallOption) (*DmeshResponse, error)
	StartApp(ctx context.Context, in *StartAppRequest, opts ...grpc.CallOption) (*StartAppResponse, error)
	StopApp(ctx context.Context, in *StopAppRequest, opts ...grpc.CallOption) (*StopAppResponse, error)
}

type dashboardClient struct {
	cc *grpc.ClientConn
}

func NewDashboardClient(cc *grpc.ClientConn) DashboardClient {
	return &dashboardClient{cc}
}

func (c *dashboardClient) AppsList(ctx context.Context, in *AppsListRequest, opts ...grpc.CallOption) (*AppsListResponse, error) {
	out := new(AppsListResponse)
	err := c.cc.Invoke(ctx, "/dashboard.Dashboard/AppsList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardClient) AppsInfo(ctx context.Context, in *AppsInfoRequest, opts ...grpc.CallOption) (Dashboard_AppsInfoClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Dashboard_serviceDesc.Streams[0], "/dashboard.Dashboard/AppsInfo", opts...)
	if err != nil {
		return nil, err
	}
	x := &dashboardAppsInfoClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Dashboard_AppsInfoClient interface {
	Recv() (*AppsInfoResponse, error)
	grpc.ClientStream
}

type dashboardAppsInfoClient struct {
	grpc.ClientStream
}

func (x *dashboardAppsInfoClient) Recv() (*AppsInfoResponse, error) {
	m := new(AppsInfoResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dashboardClient) AppsMetrics(ctx context.Context, in *AppsMetricsRequest, opts ...grpc.CallOption) (Dashboard_AppsMetricsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Dashboard_serviceDesc.Streams[1], "/dashboard.Dashboard/AppsMetrics", opts...)
	if err != nil {
		return nil, err
	}
	x := &dashboardAppsMetricsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Dashboard_AppsMetricsClient interface {
	Recv() (*AppMetricsResponse, error)
	grpc.ClientStream
}

type dashboardAppsMetricsClient struct {
	grpc.ClientStream
}

func (x *dashboardAppsMetricsClient) Recv() (*AppMetricsResponse, error) {
	m := new(AppMetricsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dashboardClient) Dmesh(ctx context.Context, in *DmeshRequest, opts ...grpc.CallOption) (*DmeshResponse, error) {
	out := new(DmeshResponse)
	err := c.cc.Invoke(ctx, "/dashboard.Dashboard/Dmesh", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardClient) StartApp(ctx context.Context, in *StartAppRequest, opts ...grpc.CallOption) (*StartAppResponse, error) {
	out := new(StartAppResponse)
	err := c.cc.Invoke(ctx, "/dashboard.Dashboard/StartApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardClient) StopApp(ctx context.Context, in *StopAppRequest, opts ...grpc.CallOption) (*StopAppResponse, error) {
	out := new(StopAppResponse)
	err := c.cc.Invoke(ctx, "/dashboard.Dashboard/StopApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DashboardServer is the server API for Dashboard service.
type DashboardServer interface {
	AppsList(context.Context, *AppsListRequest) (*AppsListResponse, error)
	AppsInfo(*AppsInfoRequest, Dashboard_AppsInfoServer) error
	AppsMetrics(*AppsMetricsRequest, Dashboard_AppsMetricsServer) error
	Dmesh(context.Context, *DmeshRequest) (*DmeshResponse, error)
	StartApp(context.Context, *StartAppRequest) (*StartAppResponse, error)
	StopApp(context.Context, *StopAppRequest) (*StopAppResponse, error)
}

// UnimplementedDashboardServer can be embedded to have forward compatible implementations.
type UnimplementedDashboardServer struct {
}

func (*UnimplementedDashboardServer) AppsList(ctx context.Context, req *AppsListRequest) (*AppsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppsList not implemented")
}
func (*UnimplementedDashboardServer) AppsInfo(req *AppsInfoRequest, srv Dashboard_AppsInfoServer) error {
	return status.Errorf(codes.Unimplemented, "method AppsInfo not implemented")
}
func (*UnimplementedDashboardServer) AppsMetrics(req *AppsMetricsRequest, srv Dashboard_AppsMetricsServer) error {
	return status.Errorf(codes.Unimplemented, "method AppsMetrics not implemented")
}
func (*UnimplementedDashboardServer) Dmesh(ctx context.Context, req *DmeshRequest) (*DmeshResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dmesh not implemented")
}
func (*UnimplementedDashboardServer) StartApp(ctx context.Context, req *StartAppRequest) (*StartAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartApp not implemented")
}
func (*UnimplementedDashboardServer) StopApp(ctx context.Context, req *StopAppRequest) (*StopAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopApp not implemented")
}

func RegisterDashboardServer(s *grpc.Server, srv DashboardServer) {
	s.RegisterService(&_Dashboard_serviceDesc, srv)
}

func _Dashboard_AppsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServer).AppsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.Dashboard/AppsList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServer).AppsList(ctx, req.(*AppsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dashboard_AppsInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AppsInfoRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DashboardServer).AppsInfo(m, &dashboardAppsInfoServer{stream})
}

type Dashboard_AppsInfoServer interface {
	Send(*AppsInfoResponse) error
	grpc.ServerStream
}

type dashboardAppsInfoServer struct {
	grpc.ServerStream
}

func (x *dashboardAppsInfoServer) Send(m *AppsInfoResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Dashboard_AppsMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AppsMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DashboardServer).AppsMetrics(m, &dashboardAppsMetricsServer{stream})
}

type Dashboard_AppsMetricsServer interface {
	Send(*AppMetricsResponse) error
	grpc.ServerStream
}

type dashboardAppsMetricsServer struct {
	grpc.ServerStream
}

func (x *dashboardAppsMetricsServer) Send(m *AppMetricsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Dashboard_Dmesh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DmeshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServer).Dmesh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.Dashboard/Dmesh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServer).Dmesh(ctx, req.(*DmeshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dashboard_StartApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServer).StartApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.Dashboard/StartApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServer).StartApp(ctx, req.(*StartAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dashboard_StopApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServer).StopApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.Dashboard/StopApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServer).StopApp(ctx, req.(*StopAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dashboard_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dashboard.Dashboard",
	HandlerType: (*DashboardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppsList",
			Handler:    _Dashboard_AppsList_Handler,
		},
		{
			MethodName: "Dmesh",
			Handler:    _Dashboard_Dmesh_Handler,
		},
		{
			MethodName: "StartApp",
			Handler:    _Dashboard_StartApp_Handler,
		},
		{
			MethodName: "StopApp",
			Handler:    _Dashboard_StopApp_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AppsInfo",
			Handler:       _Dashboard_AppsInfo_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AppsMetrics",
			Handler:       _Dashboard_AppsMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dashboard.proto",
}
