// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dfuse/eosio/accounthist/v1/accounthist.proto

package pbaccounthist

import (
	context "context"
	fmt "fmt"
	v1 "github.com/dfuse-io/dfuse-eosio/pb/dfuse/eosio/codec/v1"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetActionsRequest struct {
	Account                string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	ExclusiveUpperBoundKey []byte   `protobuf:"bytes,2,opt,name=exclusive_upper_bound_key,json=exclusiveUpperBoundKey,proto3" json:"exclusive_upper_bound_key,omitempty"`
	Count                  uint32   `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *GetActionsRequest) Reset()         { *m = GetActionsRequest{} }
func (m *GetActionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetActionsRequest) ProtoMessage()    {}
func (*GetActionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c22ddb60199ece6, []int{0}
}

func (m *GetActionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActionsRequest.Unmarshal(m, b)
}
func (m *GetActionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActionsRequest.Marshal(b, m, deterministic)
}
func (m *GetActionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActionsRequest.Merge(m, src)
}
func (m *GetActionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetActionsRequest.Size(m)
}
func (m *GetActionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetActionsRequest proto.InternalMessageInfo

func (m *GetActionsRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *GetActionsRequest) GetExclusiveUpperBoundKey() []byte {
	if m != nil {
		return m.ExclusiveUpperBoundKey
	}
	return nil
}

func (m *GetActionsRequest) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ActionData struct {
	Key                  []byte          `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	SequenceNumber       uint64          `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	ActionTrace          *v1.ActionTrace `protobuf:"bytes,3,opt,name=action_trace,json=actionTrace,proto3" json:"action_trace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ActionData) Reset()         { *m = ActionData{} }
func (m *ActionData) String() string { return proto.CompactTextString(m) }
func (*ActionData) ProtoMessage()    {}
func (*ActionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c22ddb60199ece6, []int{1}
}

func (m *ActionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionData.Unmarshal(m, b)
}
func (m *ActionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionData.Marshal(b, m, deterministic)
}
func (m *ActionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionData.Merge(m, src)
}
func (m *ActionData) XXX_Size() int {
	return xxx_messageInfo_ActionData.Size(m)
}
func (m *ActionData) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionData.DiscardUnknown(m)
}

var xxx_messageInfo_ActionData proto.InternalMessageInfo

func (m *ActionData) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ActionData) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *ActionData) GetActionTrace() *v1.ActionTrace {
	if m != nil {
		return m.ActionTrace
	}
	return nil
}

func init() {
	proto.RegisterType((*GetActionsRequest)(nil), "dfuse.eosio.accounthist.v1.GetActionsRequest")
	proto.RegisterType((*ActionData)(nil), "dfuse.eosio.accounthist.v1.ActionData")
}

func init() {
	proto.RegisterFile("dfuse/eosio/accounthist/v1/accounthist.proto", fileDescriptor_4c22ddb60199ece6)
}

var fileDescriptor_4c22ddb60199ece6 = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x4f, 0xeb, 0x30,
	0x10, 0x94, 0x5f, 0xdf, 0x87, 0xde, 0xb6, 0x14, 0xb0, 0x10, 0x2a, 0x3d, 0x85, 0x1e, 0xa0, 0x07,
	0xea, 0xd0, 0x72, 0x42, 0x9c, 0x5a, 0x55, 0x02, 0xa9, 0x82, 0x43, 0x04, 0x17, 0x2e, 0x51, 0xe2,
	0x2e, 0xd4, 0x82, 0xc6, 0x21, 0xb6, 0x03, 0xbd, 0xf0, 0x0f, 0xf8, 0xcf, 0xc8, 0x76, 0x4b, 0x23,
	0xa1, 0x72, 0xdb, 0xd9, 0x1d, 0xcf, 0x64, 0x67, 0x03, 0x27, 0xd3, 0x07, 0xa3, 0x30, 0x44, 0xa9,
	0x84, 0x0c, 0x13, 0xce, 0xa5, 0xc9, 0xf4, 0x4c, 0x28, 0x1d, 0x96, 0xfd, 0x2a, 0x64, 0x79, 0x21,
	0xb5, 0xa4, 0x6d, 0xc7, 0x66, 0x8e, 0xcd, 0xaa, 0xe3, 0xb2, 0xdf, 0x0e, 0xaa, 0x4a, 0x5c, 0x4e,
	0x91, 0x5b, 0x0d, 0x57, 0xf8, 0xd7, 0x9d, 0x77, 0xd8, 0xbd, 0x44, 0x3d, 0xe4, 0x5a, 0xc8, 0x4c,
	0x45, 0xf8, 0x62, 0x50, 0x69, 0xda, 0x82, 0x7f, 0x4b, 0xa1, 0x16, 0x09, 0x48, 0xf7, 0x7f, 0xb4,
	0x82, 0xf4, 0x1c, 0x0e, 0xf0, 0x8d, 0x3f, 0x1b, 0x25, 0x4a, 0x8c, 0x4d, 0x9e, 0x63, 0x11, 0xa7,
	0xd2, 0x64, 0xd3, 0xf8, 0x09, 0x17, 0xad, 0x5f, 0x01, 0xe9, 0x36, 0xa2, 0xfd, 0x2f, 0xc2, 0x9d,
	0x9d, 0x8f, 0xec, 0x78, 0x82, 0x0b, 0xba, 0x07, 0x7f, 0xbc, 0x64, 0x2d, 0x20, 0xdd, 0xad, 0xc8,
	0x83, 0xce, 0x07, 0x01, 0xf0, 0xee, 0xe3, 0x44, 0x27, 0x74, 0x07, 0x6a, 0x56, 0x89, 0x38, 0x25,
	0x5b, 0xd2, 0x63, 0xd8, 0x56, 0xf6, 0xb3, 0x32, 0x8e, 0x71, 0x66, 0xe6, 0x29, 0x16, 0xce, 0xe7,
	0x77, 0xd4, 0x5c, 0xb5, 0x6f, 0x5c, 0x97, 0x8e, 0xa1, 0x91, 0x38, 0xa1, 0x58, 0x17, 0x09, 0x47,
	0x67, 0x53, 0x1f, 0x1c, 0xb2, 0x6a, 0x3c, 0x7e, 0xf3, 0xb2, 0xcf, 0xbc, 0xe5, 0xad, 0x25, 0x46,
	0xf5, 0x64, 0x0d, 0x06, 0xaf, 0xd0, 0x1c, 0xfa, 0x5d, 0xaf, 0x84, 0xd2, 0xb2, 0x58, 0x50, 0x04,
	0x58, 0x27, 0x44, 0x7b, 0x6c, 0x73, 0xdc, 0xec, 0x5b, 0x92, 0xed, 0xa3, 0x9f, 0xe8, 0xeb, 0xbd,
	0x4f, 0xc9, 0xe8, 0xfa, 0x7e, 0xf2, 0x28, 0xf4, 0xcc, 0xa4, 0x8c, 0xcb, 0x79, 0xe8, 0x5e, 0xf5,
	0x84, 0x5c, 0x16, 0xfe, 0x80, 0x79, 0x1a, 0x6e, 0xfe, 0x33, 0x2e, 0xf2, 0xb4, 0xd2, 0x48, 0xff,
	0xba, 0xf3, 0x9e, 0x7d, 0x06, 0x00, 0x00, 0xff, 0xff, 0x61, 0xf5, 0x4a, 0xdf, 0x4c, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountHistoryClient is the client API for AccountHistory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountHistoryClient interface {
	GetActions(ctx context.Context, in *GetActionsRequest, opts ...grpc.CallOption) (AccountHistory_GetActionsClient, error)
}

type accountHistoryClient struct {
	cc *grpc.ClientConn
}

func NewAccountHistoryClient(cc *grpc.ClientConn) AccountHistoryClient {
	return &accountHistoryClient{cc}
}

func (c *accountHistoryClient) GetActions(ctx context.Context, in *GetActionsRequest, opts ...grpc.CallOption) (AccountHistory_GetActionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AccountHistory_serviceDesc.Streams[0], "/dfuse.eosio.accounthist.v1.AccountHistory/GetActions", opts...)
	if err != nil {
		return nil, err
	}
	x := &accountHistoryGetActionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AccountHistory_GetActionsClient interface {
	Recv() (*ActionData, error)
	grpc.ClientStream
}

type accountHistoryGetActionsClient struct {
	grpc.ClientStream
}

func (x *accountHistoryGetActionsClient) Recv() (*ActionData, error) {
	m := new(ActionData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AccountHistoryServer is the server API for AccountHistory service.
type AccountHistoryServer interface {
	GetActions(*GetActionsRequest, AccountHistory_GetActionsServer) error
}

// UnimplementedAccountHistoryServer can be embedded to have forward compatible implementations.
type UnimplementedAccountHistoryServer struct {
}

func (*UnimplementedAccountHistoryServer) GetActions(req *GetActionsRequest, srv AccountHistory_GetActionsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetActions not implemented")
}

func RegisterAccountHistoryServer(s *grpc.Server, srv AccountHistoryServer) {
	s.RegisterService(&_AccountHistory_serviceDesc, srv)
}

func _AccountHistory_GetActions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetActionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AccountHistoryServer).GetActions(m, &accountHistoryGetActionsServer{stream})
}

type AccountHistory_GetActionsServer interface {
	Send(*ActionData) error
	grpc.ServerStream
}

type accountHistoryGetActionsServer struct {
	grpc.ServerStream
}

func (x *accountHistoryGetActionsServer) Send(m *ActionData) error {
	return x.ServerStream.SendMsg(m)
}

var _AccountHistory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dfuse.eosio.accounthist.v1.AccountHistory",
	HandlerType: (*AccountHistoryServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetActions",
			Handler:       _AccountHistory_GetActions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dfuse/eosio/accounthist/v1/accounthist.proto",
}
