// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dfuse/eosio/abicodec/v1/abicodec.proto

package pbabicodec

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DecodeTableRequest struct {
	Account    string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Table      string `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	AtBlockNum uint32 `protobuf:"varint,4,opt,name=atBlockNum,proto3" json:"atBlockNum,omitempty"`
	// Binary payload, decoded from hex_data here and there.
	Payload              []byte   `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecodeTableRequest) Reset()         { *m = DecodeTableRequest{} }
func (m *DecodeTableRequest) String() string { return proto.CompactTextString(m) }
func (*DecodeTableRequest) ProtoMessage()    {}
func (*DecodeTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6174012c24e1a081, []int{0}
}

func (m *DecodeTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecodeTableRequest.Unmarshal(m, b)
}
func (m *DecodeTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecodeTableRequest.Marshal(b, m, deterministic)
}
func (m *DecodeTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecodeTableRequest.Merge(m, src)
}
func (m *DecodeTableRequest) XXX_Size() int {
	return xxx_messageInfo_DecodeTableRequest.Size(m)
}
func (m *DecodeTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DecodeTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DecodeTableRequest proto.InternalMessageInfo

func (m *DecodeTableRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *DecodeTableRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *DecodeTableRequest) GetAtBlockNum() uint32 {
	if m != nil {
		return m.AtBlockNum
	}
	return 0
}

func (m *DecodeTableRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type DecodeActionRequest struct {
	Account    string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Action     string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	AtBlockNum uint32 `protobuf:"varint,4,opt,name=atBlockNum,proto3" json:"atBlockNum,omitempty"`
	// Binary payload, decoded from hex_data here and there.
	Payload              []byte   `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecodeActionRequest) Reset()         { *m = DecodeActionRequest{} }
func (m *DecodeActionRequest) String() string { return proto.CompactTextString(m) }
func (*DecodeActionRequest) ProtoMessage()    {}
func (*DecodeActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6174012c24e1a081, []int{1}
}

func (m *DecodeActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecodeActionRequest.Unmarshal(m, b)
}
func (m *DecodeActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecodeActionRequest.Marshal(b, m, deterministic)
}
func (m *DecodeActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecodeActionRequest.Merge(m, src)
}
func (m *DecodeActionRequest) XXX_Size() int {
	return xxx_messageInfo_DecodeActionRequest.Size(m)
}
func (m *DecodeActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DecodeActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DecodeActionRequest proto.InternalMessageInfo

func (m *DecodeActionRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *DecodeActionRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *DecodeActionRequest) GetAtBlockNum() uint32 {
	if m != nil {
		return m.AtBlockNum
	}
	return 0
}

func (m *DecodeActionRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type GetAbiRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	AtBlockNum           uint32   `protobuf:"varint,4,opt,name=atBlockNum,proto3" json:"atBlockNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAbiRequest) Reset()         { *m = GetAbiRequest{} }
func (m *GetAbiRequest) String() string { return proto.CompactTextString(m) }
func (*GetAbiRequest) ProtoMessage()    {}
func (*GetAbiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6174012c24e1a081, []int{2}
}

func (m *GetAbiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAbiRequest.Unmarshal(m, b)
}
func (m *GetAbiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAbiRequest.Marshal(b, m, deterministic)
}
func (m *GetAbiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAbiRequest.Merge(m, src)
}
func (m *GetAbiRequest) XXX_Size() int {
	return xxx_messageInfo_GetAbiRequest.Size(m)
}
func (m *GetAbiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAbiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAbiRequest proto.InternalMessageInfo

func (m *GetAbiRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *GetAbiRequest) GetAtBlockNum() uint32 {
	if m != nil {
		return m.AtBlockNum
	}
	return 0
}

type Response struct {
	AbiBlockNum          uint32   `protobuf:"varint,1,opt,name=abiBlockNum,proto3" json:"abiBlockNum,omitempty"`
	JsonPayload          string   `protobuf:"bytes,2,opt,name=jsonPayload,proto3" json:"jsonPayload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_6174012c24e1a081, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetAbiBlockNum() uint32 {
	if m != nil {
		return m.AbiBlockNum
	}
	return 0
}

func (m *Response) GetJsonPayload() string {
	if m != nil {
		return m.JsonPayload
	}
	return ""
}

func init() {
	proto.RegisterType((*DecodeTableRequest)(nil), "dfuse.eosio.abicodec.v1.DecodeTableRequest")
	proto.RegisterType((*DecodeActionRequest)(nil), "dfuse.eosio.abicodec.v1.DecodeActionRequest")
	proto.RegisterType((*GetAbiRequest)(nil), "dfuse.eosio.abicodec.v1.GetAbiRequest")
	proto.RegisterType((*Response)(nil), "dfuse.eosio.abicodec.v1.Response")
}

func init() {
	proto.RegisterFile("dfuse/eosio/abicodec/v1/abicodec.proto", fileDescriptor_6174012c24e1a081)
}

var fileDescriptor_6174012c24e1a081 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0x49, 0xff, 0xff, 0xb6, 0x3a, 0x6d, 0x2f, 0xab, 0x68, 0xf0, 0x20, 0xb1, 0x87, 0x52,
	0x50, 0x37, 0x54, 0x8f, 0x9e, 0x5a, 0x94, 0xe2, 0xa5, 0x48, 0xf4, 0x24, 0x88, 0xec, 0x6e, 0x57,
	0x5d, 0x6d, 0x33, 0xb1, 0xbb, 0x29, 0x78, 0x11, 0xfc, 0x22, 0x7e, 0x56, 0xc9, 0x26, 0x0d, 0x29,
	0x12, 0x52, 0xf0, 0xb6, 0x6f, 0xf6, 0xc7, 0xcc, 0x63, 0x1e, 0x03, 0xbd, 0xe9, 0x53, 0xac, 0xa5,
	0x2f, 0x51, 0x2b, 0xf4, 0x19, 0x57, 0x02, 0xa7, 0x52, 0xf8, 0xcb, 0x41, 0xfe, 0xa6, 0xd1, 0x02,
	0x0d, 0x92, 0x7d, 0xcb, 0x51, 0xcb, 0xd1, 0xfc, 0x6f, 0x39, 0xe8, 0x7e, 0x02, 0xb9, 0x94, 0x89,
	0xba, 0x63, 0x7c, 0x26, 0x03, 0xf9, 0x1e, 0x4b, 0x6d, 0x88, 0x0b, 0x4d, 0x26, 0x04, 0xc6, 0xa1,
	0x71, 0x1d, 0xcf, 0xe9, 0x6f, 0x07, 0x2b, 0x49, 0x76, 0xa1, 0x6e, 0x12, 0xd2, 0xfd, 0x67, 0xeb,
	0xa9, 0x20, 0x87, 0x00, 0xcc, 0x8c, 0x66, 0x28, 0xde, 0x26, 0xf1, 0xdc, 0xfd, 0xef, 0x39, 0xfd,
	0x4e, 0x50, 0xa8, 0x24, 0xfd, 0x22, 0xf6, 0x31, 0x43, 0x36, 0x75, 0xeb, 0x9e, 0xd3, 0x6f, 0x07,
	0x2b, 0xd9, 0xfd, 0x72, 0x60, 0x27, 0x35, 0x30, 0x14, 0x46, 0x61, 0x58, 0xed, 0x60, 0x0f, 0x1a,
	0xcc, 0xa2, 0x99, 0x85, 0x4c, 0xfd, 0xc1, 0xc3, 0x35, 0x74, 0xc6, 0xd2, 0x0c, 0xb9, 0xaa, 0x1e,
	0x5e, 0x31, 0xa4, 0x3b, 0x81, 0xad, 0x40, 0xea, 0x08, 0x43, 0x2d, 0x89, 0x07, 0x2d, 0xc6, 0x55,
	0x0e, 0x3b, 0x16, 0x2e, 0x96, 0x12, 0xe2, 0x55, 0x63, 0x78, 0x93, 0xd9, 0xaa, 0xd9, 0x59, 0xc5,
	0xd2, 0xd9, 0x77, 0x0d, 0x9a, 0xe9, 0x7a, 0x16, 0xe4, 0x01, 0x5a, 0x85, 0xa8, 0xc8, 0x31, 0x2d,
	0xc9, 0x94, 0xfe, 0x0e, 0xf4, 0xe0, 0xa8, 0x14, 0xce, 0xed, 0x3e, 0x42, 0xbb, 0x18, 0x04, 0x39,
	0xa9, 0xe8, 0xbf, 0x96, 0xd7, 0x26, 0x03, 0x6e, 0xa1, 0x91, 0xae, 0x99, 0xf4, 0x4a, 0xe1, 0xb5,
	0x1c, 0x36, 0x68, 0x3a, 0x1a, 0xdf, 0x5f, 0x3d, 0x2b, 0xf3, 0x12, 0x73, 0x2a, 0x70, 0xee, 0x5b,
	0xfc, 0x54, 0x61, 0xf6, 0x48, 0xcf, 0x22, 0xe2, 0x7e, 0xc9, 0x95, 0x5c, 0x44, 0x7c, 0xa5, 0x78,
	0xc3, 0x1e, 0xca, 0xf9, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7b, 0xcc, 0x11, 0x2c, 0x52, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DecoderClient is the client API for Decoder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DecoderClient interface {
	DecodeTable(ctx context.Context, in *DecodeTableRequest, opts ...grpc.CallOption) (*Response, error)
	DecodeAction(ctx context.Context, in *DecodeActionRequest, opts ...grpc.CallOption) (*Response, error)
	GetAbi(ctx context.Context, in *GetAbiRequest, opts ...grpc.CallOption) (*Response, error)
}

type decoderClient struct {
	cc grpc.ClientConnInterface
}

func NewDecoderClient(cc grpc.ClientConnInterface) DecoderClient {
	return &decoderClient{cc}
}

func (c *decoderClient) DecodeTable(ctx context.Context, in *DecodeTableRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/dfuse.eosio.abicodec.v1.Decoder/DecodeTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decoderClient) DecodeAction(ctx context.Context, in *DecodeActionRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/dfuse.eosio.abicodec.v1.Decoder/DecodeAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decoderClient) GetAbi(ctx context.Context, in *GetAbiRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/dfuse.eosio.abicodec.v1.Decoder/GetAbi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DecoderServer is the server API for Decoder service.
type DecoderServer interface {
	DecodeTable(context.Context, *DecodeTableRequest) (*Response, error)
	DecodeAction(context.Context, *DecodeActionRequest) (*Response, error)
	GetAbi(context.Context, *GetAbiRequest) (*Response, error)
}

// UnimplementedDecoderServer can be embedded to have forward compatible implementations.
type UnimplementedDecoderServer struct {
}

func (*UnimplementedDecoderServer) DecodeTable(ctx context.Context, req *DecodeTableRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecodeTable not implemented")
}
func (*UnimplementedDecoderServer) DecodeAction(ctx context.Context, req *DecodeActionRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecodeAction not implemented")
}
func (*UnimplementedDecoderServer) GetAbi(ctx context.Context, req *GetAbiRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAbi not implemented")
}

func RegisterDecoderServer(s *grpc.Server, srv DecoderServer) {
	s.RegisterService(&_Decoder_serviceDesc, srv)
}

func _Decoder_DecodeTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecodeTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecoderServer).DecodeTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dfuse.eosio.abicodec.v1.Decoder/DecodeTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecoderServer).DecodeTable(ctx, req.(*DecodeTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Decoder_DecodeAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecodeActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecoderServer).DecodeAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dfuse.eosio.abicodec.v1.Decoder/DecodeAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecoderServer).DecodeAction(ctx, req.(*DecodeActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Decoder_GetAbi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAbiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecoderServer).GetAbi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dfuse.eosio.abicodec.v1.Decoder/GetAbi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecoderServer).GetAbi(ctx, req.(*GetAbiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Decoder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dfuse.eosio.abicodec.v1.Decoder",
	HandlerType: (*DecoderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DecodeTable",
			Handler:    _Decoder_DecodeTable_Handler,
		},
		{
			MethodName: "DecodeAction",
			Handler:    _Decoder_DecodeAction_Handler,
		},
		{
			MethodName: "GetAbi",
			Handler:    _Decoder_GetAbi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dfuse/eosio/abicodec/v1/abicodec.proto",
}
