((web-mode . ((indent-tabs-mode . nil)
              (web-mode-code-indent-offset . 2)
              (web-mode-css-indent-offset . 2)
              (web-mode-markup-indent-offset . 2)
              (web-mode-indent-style . 2)
              (web-mode-script-padding . 2)
              (web-mode-style-padding . 2)
              (web-mode-code-indent-offset . 2)
              (web-mode-css-indent-offset . 2)
              (web-mode-markup-indent-offset . 2)
              (web-mode-indent-style . 2)
              (web-mode-script-padding . 0)
              (web-mode-style-padding . 0)
              (sgml-basic-offset . 2)))
 (typescript-mode . ((typescript-indent-level . 2)
                     (typescript-expr-indent-offset . 0)))
)
