
@startuml

title Search components interactions

node "relayer 1, relayer 2" as relayers
node "router 1, router 2" as routers
node "archive 1, archive 2" as archives
node "live 1, live 2" as lives

node indexer
node forkresolver
node "dmesh (etcd)" as dmesh

indexer --> archives : via Object Store

dmesh <. archives
dmesh <. lives
dmesh <. routers

forkresolver <-- routers
archives <-- routers
lives <-- routers

relayers <-- indexer
relayers <-- lives   : gRPC


actor user

routers --> user

@enduml
