// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dfuse/eosio/eosdb/v1/eosdb.proto

package pbeosdb

import (
	fmt "fmt"
	v1 "github.com/dfuse-io/dfuse-eosio/pb/dfuse/eosio/codec/v1"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ImplicitTrxRow struct {
	// Primary key to include: transaction_id and block_id
	SignedTrx            *v1.SignedTransaction `protobuf:"bytes,1,opt,name=signed_trx,json=signedTrx,proto3" json:"signed_trx,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ImplicitTrxRow) Reset()         { *m = ImplicitTrxRow{} }
func (m *ImplicitTrxRow) String() string { return proto.CompactTextString(m) }
func (*ImplicitTrxRow) ProtoMessage()    {}
func (*ImplicitTrxRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_c57a3e77a627e851, []int{0}
}

func (m *ImplicitTrxRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImplicitTrxRow.Unmarshal(m, b)
}
func (m *ImplicitTrxRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImplicitTrxRow.Marshal(b, m, deterministic)
}
func (m *ImplicitTrxRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImplicitTrxRow.Merge(m, src)
}
func (m *ImplicitTrxRow) XXX_Size() int {
	return xxx_messageInfo_ImplicitTrxRow.Size(m)
}
func (m *ImplicitTrxRow) XXX_DiscardUnknown() {
	xxx_messageInfo_ImplicitTrxRow.DiscardUnknown(m)
}

var xxx_messageInfo_ImplicitTrxRow proto.InternalMessageInfo

func (m *ImplicitTrxRow) GetSignedTrx() *v1.SignedTransaction {
	if m != nil {
		return m.SignedTrx
	}
	return nil
}

func (m *ImplicitTrxRow) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TrxRow struct {
	SignedTrx            *v1.SignedTransaction  `protobuf:"bytes,1,opt,name=signed_trx,json=signedTrx,proto3" json:"signed_trx,omitempty"`
	Receipt              *v1.TransactionReceipt `protobuf:"bytes,2,opt,name=receipt,proto3" json:"receipt,omitempty"`
	PublicKeys           *v1.PublicKeys         `protobuf:"bytes,3,opt,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TrxRow) Reset()         { *m = TrxRow{} }
func (m *TrxRow) String() string { return proto.CompactTextString(m) }
func (*TrxRow) ProtoMessage()    {}
func (*TrxRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_c57a3e77a627e851, []int{1}
}

func (m *TrxRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrxRow.Unmarshal(m, b)
}
func (m *TrxRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrxRow.Marshal(b, m, deterministic)
}
func (m *TrxRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrxRow.Merge(m, src)
}
func (m *TrxRow) XXX_Size() int {
	return xxx_messageInfo_TrxRow.Size(m)
}
func (m *TrxRow) XXX_DiscardUnknown() {
	xxx_messageInfo_TrxRow.DiscardUnknown(m)
}

var xxx_messageInfo_TrxRow proto.InternalMessageInfo

func (m *TrxRow) GetSignedTrx() *v1.SignedTransaction {
	if m != nil {
		return m.SignedTrx
	}
	return nil
}

func (m *TrxRow) GetReceipt() *v1.TransactionReceipt {
	if m != nil {
		return m.Receipt
	}
	return nil
}

func (m *TrxRow) GetPublicKeys() *v1.PublicKeys {
	if m != nil {
		return m.PublicKeys
	}
	return nil
}

type TrxTraceRow struct {
	TrxTrace             *v1.TransactionTrace `protobuf:"bytes,1,opt,name=trx_trace,json=trxTrace,proto3" json:"trx_trace,omitempty"`
	BlockHeader          *v1.BlockHeader      `protobuf:"bytes,2,opt,name=block_header,json=blockHeader,proto3" json:"block_header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TrxTraceRow) Reset()         { *m = TrxTraceRow{} }
func (m *TrxTraceRow) String() string { return proto.CompactTextString(m) }
func (*TrxTraceRow) ProtoMessage()    {}
func (*TrxTraceRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_c57a3e77a627e851, []int{2}
}

func (m *TrxTraceRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrxTraceRow.Unmarshal(m, b)
}
func (m *TrxTraceRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrxTraceRow.Marshal(b, m, deterministic)
}
func (m *TrxTraceRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrxTraceRow.Merge(m, src)
}
func (m *TrxTraceRow) XXX_Size() int {
	return xxx_messageInfo_TrxTraceRow.Size(m)
}
func (m *TrxTraceRow) XXX_DiscardUnknown() {
	xxx_messageInfo_TrxTraceRow.DiscardUnknown(m)
}

var xxx_messageInfo_TrxTraceRow proto.InternalMessageInfo

func (m *TrxTraceRow) GetTrxTrace() *v1.TransactionTrace {
	if m != nil {
		return m.TrxTrace
	}
	return nil
}

func (m *TrxTraceRow) GetBlockHeader() *v1.BlockHeader {
	if m != nil {
		return m.BlockHeader
	}
	return nil
}

type DtrxRow struct {
	SignedTrx            *v1.SignedTransaction `protobuf:"bytes,1,opt,name=signed_trx,json=signedTrx,proto3" json:"signed_trx,omitempty"`
	CreatedBy            *v1.ExtDTrxOp         `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CanceledBy           *v1.ExtDTrxOp         `protobuf:"bytes,3,opt,name=canceled_by,json=canceledBy,proto3" json:"canceled_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DtrxRow) Reset()         { *m = DtrxRow{} }
func (m *DtrxRow) String() string { return proto.CompactTextString(m) }
func (*DtrxRow) ProtoMessage()    {}
func (*DtrxRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_c57a3e77a627e851, []int{3}
}

func (m *DtrxRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DtrxRow.Unmarshal(m, b)
}
func (m *DtrxRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DtrxRow.Marshal(b, m, deterministic)
}
func (m *DtrxRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DtrxRow.Merge(m, src)
}
func (m *DtrxRow) XXX_Size() int {
	return xxx_messageInfo_DtrxRow.Size(m)
}
func (m *DtrxRow) XXX_DiscardUnknown() {
	xxx_messageInfo_DtrxRow.DiscardUnknown(m)
}

var xxx_messageInfo_DtrxRow proto.InternalMessageInfo

func (m *DtrxRow) GetSignedTrx() *v1.SignedTransaction {
	if m != nil {
		return m.SignedTrx
	}
	return nil
}

func (m *DtrxRow) GetCreatedBy() *v1.ExtDTrxOp {
	if m != nil {
		return m.CreatedBy
	}
	return nil
}

func (m *DtrxRow) GetCanceledBy() *v1.ExtDTrxOp {
	if m != nil {
		return m.CanceledBy
	}
	return nil
}

type BlockRow struct {
	Block                *v1.Block           `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	ImplicitTrxRefs      *v1.TransactionRefs `protobuf:"bytes,2,opt,name=implicit_trx_refs,json=implicitTrxRefs,proto3" json:"implicit_trx_refs,omitempty"`
	TrxRefs              *v1.TransactionRefs `protobuf:"bytes,3,opt,name=trx_refs,json=trxRefs,proto3" json:"trx_refs,omitempty"`
	TraceRefs            *v1.TransactionRefs `protobuf:"bytes,4,opt,name=trace_refs,json=traceRefs,proto3" json:"trace_refs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BlockRow) Reset()         { *m = BlockRow{} }
func (m *BlockRow) String() string { return proto.CompactTextString(m) }
func (*BlockRow) ProtoMessage()    {}
func (*BlockRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_c57a3e77a627e851, []int{4}
}

func (m *BlockRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRow.Unmarshal(m, b)
}
func (m *BlockRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRow.Marshal(b, m, deterministic)
}
func (m *BlockRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRow.Merge(m, src)
}
func (m *BlockRow) XXX_Size() int {
	return xxx_messageInfo_BlockRow.Size(m)
}
func (m *BlockRow) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRow.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRow proto.InternalMessageInfo

func (m *BlockRow) GetBlock() *v1.Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *BlockRow) GetImplicitTrxRefs() *v1.TransactionRefs {
	if m != nil {
		return m.ImplicitTrxRefs
	}
	return nil
}

func (m *BlockRow) GetTrxRefs() *v1.TransactionRefs {
	if m != nil {
		return m.TrxRefs
	}
	return nil
}

func (m *BlockRow) GetTraceRefs() *v1.TransactionRefs {
	if m != nil {
		return m.TraceRefs
	}
	return nil
}

type AccountRow struct {
	// Key will be account:block_id    // block_id, block_num and account implicit in key
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Creator              string               `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	BlockId              string               `protobuf:"bytes,3,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	TrxId                string               `protobuf:"bytes,4,opt,name=trx_id,json=trxId,proto3" json:"trx_id,omitempty"`
	BlockTime            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=block_time,json=blockTime,proto3" json:"block_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AccountRow) Reset()         { *m = AccountRow{} }
func (m *AccountRow) String() string { return proto.CompactTextString(m) }
func (*AccountRow) ProtoMessage()    {}
func (*AccountRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_c57a3e77a627e851, []int{5}
}

func (m *AccountRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRow.Unmarshal(m, b)
}
func (m *AccountRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRow.Marshal(b, m, deterministic)
}
func (m *AccountRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRow.Merge(m, src)
}
func (m *AccountRow) XXX_Size() int {
	return xxx_messageInfo_AccountRow.Size(m)
}
func (m *AccountRow) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRow.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRow proto.InternalMessageInfo

func (m *AccountRow) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AccountRow) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *AccountRow) GetBlockId() string {
	if m != nil {
		return m.BlockId
	}
	return ""
}

func (m *AccountRow) GetTrxId() string {
	if m != nil {
		return m.TrxId
	}
	return ""
}

func (m *AccountRow) GetBlockTime() *timestamp.Timestamp {
	if m != nil {
		return m.BlockTime
	}
	return nil
}

func init() {
	proto.RegisterType((*ImplicitTrxRow)(nil), "dfuse.eosio.eosdb.v1.ImplicitTrxRow")
	proto.RegisterType((*TrxRow)(nil), "dfuse.eosio.eosdb.v1.TrxRow")
	proto.RegisterType((*TrxTraceRow)(nil), "dfuse.eosio.eosdb.v1.TrxTraceRow")
	proto.RegisterType((*DtrxRow)(nil), "dfuse.eosio.eosdb.v1.DtrxRow")
	proto.RegisterType((*BlockRow)(nil), "dfuse.eosio.eosdb.v1.BlockRow")
	proto.RegisterType((*AccountRow)(nil), "dfuse.eosio.eosdb.v1.AccountRow")
}

func init() { proto.RegisterFile("dfuse/eosio/eosdb/v1/eosdb.proto", fileDescriptor_c57a3e77a627e851) }

var fileDescriptor_c57a3e77a627e851 = []byte{
	// 562 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0xfb, 0x97, 0x78, 0x8c, 0x40, 0xac, 0x40, 0x0a, 0xe5, 0xd0, 0x60, 0x09, 0xe8, 0x05,
	0x5b, 0x29, 0x27, 0x84, 0x04, 0x6d, 0x08, 0x88, 0x8a, 0x03, 0xb0, 0xf8, 0xc4, 0xc5, 0xb2, 0xd7,
	0x9b, 0x74, 0x55, 0xc7, 0x6b, 0xad, 0x37, 0xc1, 0x79, 0x93, 0xbe, 0x01, 0x0f, 0xc4, 0x81, 0xd7,
	0x41, 0x3b, 0xbb, 0x6e, 0x83, 0x14, 0x41, 0x2b, 0xf5, 0x12, 0xcd, 0x24, 0xdf, 0xf7, 0xcd, 0x7e,
	0x93, 0x99, 0x81, 0x61, 0x31, 0x5d, 0x34, 0x3c, 0xe6, 0xb2, 0x11, 0xd2, 0x7c, 0x16, 0x79, 0xbc,
	0x1c, 0xd9, 0x20, 0xaa, 0x95, 0xd4, 0x92, 0x3c, 0x40, 0x44, 0x84, 0x88, 0xc8, 0xfe, 0xb0, 0x1c,
	0xed, 0xff, 0xc5, 0x63, 0xb2, 0xe0, 0xcc, 0xf0, 0x30, 0xb0, 0xbc, 0xfd, 0x83, 0x99, 0x94, 0xb3,
	0x92, 0xc7, 0x98, 0xe5, 0x8b, 0x69, 0xac, 0xc5, 0x9c, 0x37, 0x3a, 0x9b, 0xd7, 0x16, 0x10, 0x96,
	0x70, 0xf7, 0x74, 0x5e, 0x97, 0x82, 0x09, 0x9d, 0xa8, 0x96, 0xca, 0x1f, 0xe4, 0x03, 0x40, 0x23,
	0x66, 0x15, 0x2f, 0x52, 0xad, 0xda, 0x81, 0x37, 0xf4, 0x0e, 0x83, 0xa3, 0xe7, 0xd1, 0x7a, 0x7d,
	0x5b, 0x60, 0x39, 0x8a, 0xbe, 0x21, 0x2e, 0x51, 0x59, 0xd5, 0x64, 0x4c, 0x0b, 0x59, 0x51, 0xbf,
	0x71, 0x5f, 0xb5, 0x84, 0xc0, 0x4e, 0x95, 0xcd, 0xf9, 0x60, 0x6b, 0xe8, 0x1d, 0xfa, 0x14, 0xe3,
	0xf0, 0xb7, 0x07, 0x7b, 0xb7, 0x5c, 0x66, 0x0c, 0x3d, 0xc5, 0x19, 0x17, 0xb5, 0xc6, 0x4a, 0xc1,
	0xd1, 0xe1, 0x66, 0x91, 0x75, 0xba, 0xc5, 0xd3, 0x8e, 0x48, 0x4e, 0x20, 0xa8, 0x17, 0x79, 0x29,
	0x58, 0x7a, 0xce, 0x57, 0xcd, 0x60, 0x1b, 0x75, 0x86, 0x9b, 0x75, 0xbe, 0x20, 0xf0, 0x13, 0x5f,
	0x35, 0x14, 0xea, 0xcb, 0x38, 0xbc, 0xf0, 0x20, 0x48, 0x54, 0x9b, 0xa8, 0x8c, 0x71, 0x63, 0xef,
	0x1d, 0xf8, 0x5a, 0xb5, 0xa9, 0x36, 0xb9, 0x73, 0xf7, 0xec, 0xbf, 0x0f, 0xb3, 0xec, 0xbe, 0x76,
	0x3a, 0x64, 0x02, 0x77, 0xf2, 0x52, 0xb2, 0xf3, 0xf4, 0x8c, 0x67, 0x05, 0x57, 0xce, 0xe0, 0x93,
	0xcd, 0x3a, 0x63, 0x83, 0xfc, 0x88, 0x40, 0x1a, 0xe4, 0x57, 0x49, 0xf8, 0xcb, 0x83, 0xde, 0x44,
	0xdf, 0x6e, 0xd7, 0xdf, 0x00, 0x30, 0xc5, 0x33, 0xcd, 0x8b, 0x34, 0x5f, 0xb9, 0x77, 0x1d, 0x6c,
	0xd6, 0x79, 0xdf, 0xea, 0x49, 0xa2, 0xda, 0xcf, 0x35, 0xf5, 0x1d, 0x65, 0xbc, 0x22, 0xc7, 0x10,
	0xb0, 0xac, 0x62, 0xbc, 0xb4, 0x02, 0xdb, 0xd7, 0x13, 0x80, 0x8e, 0x33, 0x5e, 0x85, 0x17, 0x5b,
	0xd0, 0x47, 0xcb, 0xc6, 0xd6, 0x08, 0x76, 0xd1, 0xb1, 0x73, 0xf4, 0xf8, 0x1f, 0x1d, 0xa2, 0x16,
	0x49, 0xbe, 0xc2, 0x7d, 0xe1, 0x06, 0xdf, 0xf4, 0x22, 0x55, 0x7c, 0xda, 0x38, 0x23, 0x4f, 0xaf,
	0x31, 0x41, 0xd3, 0x86, 0xde, 0x13, 0x6b, 0x8b, 0xc3, 0xa7, 0x0d, 0x39, 0x86, 0xfe, 0xa5, 0xd2,
	0xf6, 0x4d, 0x94, 0x7a, 0xda, 0x29, 0x4c, 0x00, 0x70, 0x62, 0xac, 0xc6, 0xce, 0x4d, 0x34, 0x7c,
	0x24, 0x9a, 0x30, 0xfc, 0xe9, 0x01, 0x9c, 0x30, 0x26, 0x17, 0x95, 0x36, 0xcd, 0xe9, 0x16, 0xd1,
	0xbb, 0x5a, 0x44, 0x32, 0x80, 0x1e, 0xfe, 0x19, 0x52, 0xb9, 0xfd, 0xec, 0x52, 0xf2, 0x08, 0xfa,
	0x76, 0xe6, 0x44, 0x81, 0x26, 0x7c, 0xda, 0xc3, 0xfc, 0xb4, 0x20, 0x0f, 0x61, 0xcf, 0xf8, 0x13,
	0x05, 0xbe, 0xcc, 0xa7, 0xbb, 0x5a, 0xb5, 0xa7, 0x05, 0x79, 0x05, 0x60, 0x19, 0xe6, 0xb6, 0x0c,
	0x76, 0xf1, 0xd1, 0xfb, 0x91, 0x3d, 0x3c, 0x51, 0x77, 0x78, 0xa2, 0xa4, 0x3b, 0x3c, 0xd4, 0x47,
	0xb4, 0xc9, 0xc7, 0x27, 0xdf, 0xdf, 0xce, 0x84, 0x3e, 0x5b, 0xe4, 0x11, 0x93, 0xf3, 0x18, 0x7d,
	0xbe, 0x10, 0xd2, 0x05, 0xf6, 0xac, 0xd5, 0x79, 0xbc, 0xe9, 0x3a, 0xbe, 0xae, 0x73, 0x0c, 0xf3,
	0x3d, 0xac, 0xf0, 0xf2, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x92, 0x5c, 0x17, 0x44, 0x05,
	0x00, 0x00,
}
